KLP_version = 7
Run_loot_table = {
----- Ewü  2022/02/10 P2 Loot
----- Lome 2022/02/11 P3 Loot
----- Ewü  2022/05/29 P5 Loot
----- Lome/Brot 2023/01/19 WotLK P2 Loot
----- Ewü/Lome 2023/10/15 WotLK P4 Loot
----- Ewü/Lome 2023/11/15 WotLK P4 Loot Adjustments
-----SSC
-----Trashloot
{["loot_id"] = "40194", ["loot_name"] = "Blanketing Robes of Snow", ["prio"] = "Prio: Diszi > Resto Druid",},
{["loot_id"] = "40539", ["loot_name"] = "Chestguard of the Recluse", ["prio"] = "Prio: Rogue/Feral > Arms > Fury > Frost/Ret",},
{["loot_id"] = "40558", ["loot_name"] = "Arcanic Tramplers", ["prio"] = "Prio: Caster DDs",},
{["loot_id"] = "40549", ["loot_name"] = "Boots of the Renewed Flight", ["prio"] = "Prio: Hunter > Enhancer > DPS Warris",},
{["loot_id"] = "40592", ["loot_name"] = "Boots of Healing Energies", ["prio"] = "Prio: Healpala",},
{["loot_id"] = "40591", ["loot_name"] = "Melancholy Sabatons", ["prio"] = "Prio: DPS Warri > Frost > Ret > Unholy",},
{["loot_id"] = "40541", ["loot_name"] = "Frosted Adroit Handguards", ["prio"] = "Prio: Arms > Feral > Rogue > Hunter > Ret/Fury",},
{["loot_id"] = "40564", ["loot_name"] = "Winter Spectacle Gloves", ["prio"] = "Prio: Resto Schami > Heal Pala",},
{["loot_id"] = "40562", ["loot_name"] = "Hood of Rationality", ["prio"] = "Prio: Shadow > Diszi > Warlock / Mage",},
{["loot_id"] = "40543", ["loot_name"] = "Blue Aspect Helm", ["prio"] = "Prio: Hunter/Enhancer > DPS Warri",},
{["loot_id"] = "40560", ["loot_name"] = "Leggings of the Wanton Spellcaster", ["prio"] = "Prio: Affli > Boomkin > Shadow",},
{["loot_id"] = "40589", ["loot_name"] = "Legplates of Souvereignty", ["prio"] = "Prio: Prot Pala > Blood",},
{["loot_id"] = "44651", ["loot_name"] = "Heart of Magic", ["prio"] = "Prio: Main Prot Pala > 1. Demo > Caster > Meele/Hunter > Healer",},
{["loot_id"] = "40555", ["loot_name"] = "Mantel of Dissemination", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "40594", ["loot_name"] = "Spaulders of Catatonia", ["prio"] = "Prio: Boomkin",},
{["loot_id"] = "40590", ["loot_name"] = "Elevated Lair Pauldrons", ["prio"] = "Prio: Holy Pala",},
{["loot_id"] = "40561", ["loot_name"] = "Leash of Heedless Magic", ["prio"] = "Prio: 1. Demo > Shadow/Arcane/Diszi/Warlock",},
{["loot_id"] = "40566", ["loot_name"] = "Unravelling Strads of Sanity", ["prio"] = "Prio: Resto Druid",},
{["loot_id"] = "40588", ["loot_name"] = "Tunic of the Artiface Guardian", ["prio"] = "Prio: Heal Pala/Resto Schami",},
{["loot_id"] = "40532", ["loot_name"] = "Living Ice Crystals", ["prio"] = "Prio: ",},
{["loot_id"] = "40531", ["loot_name"] = "Mark of Norgannon", ["prio"] = "Prio: Enhancer",},
{["loot_id"] = "40250", ["loot_name"] = "Aged Winter Cloak", ["prio"] = "Prio: Arms > Fury/Hunter/Frost > Rest",},
{["loot_id"] = "40254", ["loot_name"] = "Cloak of Averted Crisis", ["prio"] = "Prio: Healer > Resto Druid",},
{["loot_id"] = "40252", ["loot_name"] = "Cloak of the Shadowed Sun", ["prio"] = "Prio: Blood / Feral Bear > Prot Pala",},
{["loot_id"] = "40405", ["loot_name"] = "Cape of the Unworthy Wizard", ["prio"] = "Prio: 1. Demo > Shadow > Diszi > Boomkin/Warlock > Arcane",},
{["loot_id"] = "40403", ["loot_name"] = "Drape of the Deadly Foe", ["prio"] = "Prio: Rogue/Feral Cat  > Enhancer/Ret > Unholy",},
{["loot_id"] = "40062", ["loot_name"] = "Digested Silken Robes", ["prio"] = "Prio: Diszi",},
{["loot_id"] = "40602", ["loot_name"] = "Robes of Mutation", ["prio"] = "Prio: Diszi/Shadow",},
{["loot_id"] = "40234", ["loot_name"] = "Heigan´s Putrid Vestments", ["prio"] = "Prio: Shadow > Ele > DPS Casters",},
{["loot_id"] = "40381", ["loot_name"] = "Sympathy", ["prio"] = "Prio: Diszi/Resto Druid",},
{["loot_id"] = "39756", ["loot_name"] = "Tunic of Prejudice", ["prio"] = "Prio: Resto Druid",},
{["loot_id"] = "40277", ["loot_name"] = "Tunic of Indulengence", ["prio"] = "Prio: Feral/Rogue > Ret/DPS Warris/Hunter",},
{["loot_id"] = "40249", ["loot_name"] = "Vest of Vitality", ["prio"] = "Prio: Rest Schami",},
{["loot_id"] = "40319", ["loot_name"] = "Chestpice of Suspicion", ["prio"] = "Prio: ",},
{["loot_id"] = "39724", ["loot_name"] = "Cult´s Chestguard", ["prio"] = "Prio: Enhancer",},
{["loot_id"] = "40283", ["loot_name"] = "Fallout Impervious Tunic", ["prio"] = "Prio: Ele  >  Resto Schami / Heal Pala",},
{["loot_id"] = "40193", ["loot_name"] = "Tunic of Masked Suffering", ["prio"] = "Prio: Hunter > Enhancer",},
{["loot_id"] = "40279", ["loot_name"] = "Chestguard of the Exausted", ["prio"] = "Prio: Prot Pala",},
{["loot_id"] = "40203", ["loot_name"] = "Breastplate of Tormented Rage", ["prio"] = "Prio: Blood/Prot Pala",},
{["loot_id"] = "40210", ["loot_name"] = "Chestguard of Bitter Charms", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40365", ["loot_name"] = "Breastplate of Frozen Pain", ["prio"] = "Prio: Plate DPS",},
{["loot_id"] = "40269", ["loot_name"] = "Boots of Persuasion", ["prio"] = "Prio: Diszi > Rest",},
{["loot_id"] = "40236", ["loot_name"] = "Serene Echoes", ["prio"] = "Prio: Diszi > Resto Schami > Heal Pala >  Resto Druid",},
{["loot_id"] = "40246", ["loot_name"] = "Boots of Impetuous Ideals", ["prio"] = "Prio: Diszi (Hit) > Shadow > Warlock",},
{["loot_id"] = "40326", ["loot_name"] = "Boots of Forlorn Whishes", ["prio"] = "Prio: Diszi > Spirit Caster",},
{["loot_id"] = "39701", ["loot_name"] = "Dawnwalkers", ["prio"] = "Prio: Rouge > Feral > Ret",},
{["loot_id"] = "40243", ["loot_name"] = "Footwraps of Vile Deceit", ["prio"] = "Prio: Feral > Rogue",},
{["loot_id"] = "39734", ["loot_name"] = "Atonement Greaves", ["prio"] = "Prio: Resto Schami",},
{["loot_id"] = "40184", ["loot_name"] = "Crippled Treads", ["prio"] = "Prio: Enhancer > Hunter",},
{["loot_id"] = "40237", ["loot_name"] = "Eruption-Scarred Boots", ["prio"] = "Prio: Resto Schami > Ele > Heal Pala",},
{["loot_id"] = "40367", ["loot_name"] = "Boots of the Great Construct", ["prio"] = "Prio: Enhancer > Hunter",},
{["loot_id"] = "39717", ["loot_name"] = "Inexorable Sabatons", ["prio"] = "Prio: Prot Pala > Blood",},
{["loot_id"] = "39706", ["loot_name"] = "Sabatons of Sudden Reprisal", ["prio"] = "Prio: Unholy",},
{["loot_id"] = "40297", ["loot_name"] = "Sabatons of Endurance", ["prio"] = "Prio: Blood > Prot Pala",},
{["loot_id"] = "40187", ["loot_name"] = "Poignant Sabatons", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40206", ["loot_name"] = "Iron-Spring Jumpers", ["prio"] = "Prio: Ret > Unholy > DPS Warri/Frost",},
{["loot_id"] = "40320", ["loot_name"] = "Faithful Steel Sabatons", ["prio"] = "Prio: ",},
{["loot_id"] = "39733", ["loot_name"] = "Gloves of Token Respect", ["prio"] = "Prio: Arcane > Diszi/Resto Duid > Warlock > Boomkin",},
{["loot_id"] = "40303", ["loot_name"] = "Wraps of the Persecuted", ["prio"] = "Prio: Diszi > Resto Schami",},
{["loot_id"] = "40197", ["loot_name"] = "Cloves of the Fallen Wizard", ["prio"] = "Prio: Shadow > Warlock > Rest",},
{["loot_id"] = "40380", ["loot_name"] = "Gloves of Grandeur", ["prio"] = "Prio: Shadow > Ele > Boomkin",},
{["loot_id"] = "39727", ["loot_name"] = "Dislocating Hand", ["prio"] = "Prio: Feral/Rogue/Enhancer",},
{["loot_id"] = "40238", ["loot_name"] = "Gloves of the Dancing Bear", ["prio"] = "Prio: Boomkin > Resto Druid",},
{["loot_id"] = "40349", ["loot_name"] = "Gloves of Peaceful Death", ["prio"] = "Prio: ",},
{["loot_id"] = "40362", ["loot_name"] = "Gloves of Fast Reactions", ["prio"] = "Prio: Feral > Fury/Rogue",},
{["loot_id"] = "39718", ["loot_name"] = "Corpse Scarab Handguards", ["prio"] = "Prio: Restoschami > Heal Pala",},
{["loot_id"] = "40262", ["loot_name"] = "Gloves of Calculation", ["prio"] = "Prio: Hunter > Enhancer > DPS Warri",},
{["loot_id"] = "40302", ["loot_name"] = "Benefactor´s Gauntlets", ["prio"] = "Prio: Ele > Resto",},
{["loot_id"] = "40242", ["loot_name"] = "Grotesque Handgrips", ["prio"] = "Prio: Hunter > DPS Warri",},
{["loot_id"] = "39703", ["loot_name"] = "Rescinding Grips", ["prio"] = "Prio: Holy Pala",},
{["loot_id"] = "39726", ["loot_name"] = "Callous-Hearted Gauntlets", ["prio"] = "Prio: Blood > Prot Pala",},
{["loot_id"] = "40261", ["loot_name"] = "Crude Discolored Battlegrips", ["prio"] = "Prio: Ret > Arms > Fury",},
{["loot_id"] = "40188", ["loot_name"] = "Gauntlets of the Disobedient", ["prio"] = "Prio: Prot Pala > Blood",},
{["loot_id"] = "40316", ["loot_name"] = "Gauntlets of Guiding Touch", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40347", ["loot_name"] = "Zeliek´s Gauntlets", ["prio"] = "Prio: Unholy",},
{["loot_id"] = "40287", ["loot_name"] = "Cowl of Vanity", ["prio"] = "Prio: Diszi / Shadow > Resto Druid / Warlock / Mage",},
{["loot_id"] = "40247", ["loot_name"] = "Cowl of Innocent Delight", ["prio"] = "Prio: ",},
{["loot_id"] = "40339", ["loot_name"] = "Gothik´s Cowl", ["prio"] = "Prio: Mage > DPS Casters",},
{["loot_id"] = "40304", ["loot_name"] = "Headpice of Fungal Bloom", ["prio"] = "Prio: Resto Druid > Heal Pala/Resto Druid",},
{["loot_id"] = "40329", ["loot_name"] = "Hood of the Exodus", ["prio"] = "Prio: Feral > Rogue",},
{["loot_id"] = "40235", ["loot_name"] = "Helm of Pilgrimage", ["prio"] = "Prio: ",},
{["loot_id"] = "40340", ["loot_name"] = "Helm of Unleashed Energy", ["prio"] = "Prio: Resto Schami",},
{["loot_id"] = "40344", ["loot_name"] = "Helm of the Grave", ["prio"] = "Prio: DPS Warri > Hunter > Enchanter",},
{["loot_id"] = "40298", ["loot_name"] = "Faceguard of the Succumbed", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40328", ["loot_name"] = "Helm of Vital Protection", ["prio"] = "Prio: Blood",},
{["loot_id"] = "40366", ["loot_name"] = "Plate Helm of the Great Wyrm", ["prio"] = "Prio: ",},
{["loot_id"] = "39720", ["loot_name"] = "Leggings of Atrophy", ["prio"] = "Prio: Ele > Rest",},
{["loot_id"] = "40060", ["loot_name"] = "Distorted Limbs", ["prio"] = "Prio: 1. Demo > Resto Druid > Boomkin/Diszi/Arcane/Warlock",},
{["loot_id"] = "40376", ["loot_name"] = "Legwraps of the Defeated Dragon", ["prio"] = "Prio: 1. Demo > Rest",},
{["loot_id"] = "40398", ["loot_name"] = "Leggings of Mortal Arrogance", ["prio"] = "Prio: Diszi > Shadow > Boomkin > Rest",},
{["loot_id"] = "39761", ["loot_name"] = "Infectious Skitter Leggings", ["prio"] = "Prio: ",},
{["loot_id"] = "40285", ["loot_name"] = "Desecrated Past", ["prio"] = "Prio: ",},
{["loot_id"] = "40333", ["loot_name"] = "Leggings of Fleeting Moments", ["prio"] = "Prio: Rogue/Feral > Hunter > DPS Warri",},
{["loot_id"] = "40379", ["loot_name"] = "Legguards of the Boneyard", ["prio"] = "Prio: Resto Druid > Boomkin",},
{["loot_id"] = "40196", ["loot_name"] = "Legguards of the Undisturbed", ["prio"] = "Prio: Resto Schami > Heal Pala",},
{["loot_id"] = "40201", ["loot_name"] = "Leggings of Colossal Stries", ["prio"] = "Prio: Hunter/Enhancer",},
{["loot_id"] = "40331", ["loot_name"] = "Leggings of Failed Escape", ["prio"] = "Prio: Hunter > Enhancer > Arms > Fury",},
{["loot_id"] = "40352", ["loot_name"] = "Leggings of Voracious Shadows", ["prio"] = "Prio: Ele > Resto Schami > Heal Pala",},
{["loot_id"] = "40294", ["loot_name"] = "Riveted Abomination Leggings", ["prio"] = "Prio: Unholy > Ret > Frost > DPS Warri",},
{["loot_id"] = "40204", ["loot_name"] = "Legguards of the Apostle", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40240", ["loot_name"] = "Greaves of Turbulence", ["prio"] = "Prio: Tanks > Rest",},
{["loot_id"] = "40318", ["loot_name"] = "Legplates of Double Strikes", ["prio"] = "Prio: Arms > Frost/Fury > Unholy/Ret",},
{["loot_id"] = "40363", ["loot_name"] = "Bone-Inlaid Legguards", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40071", ["loot_name"] = "Chains of Adoration", ["prio"] = "Prio: Resto Druid > Diszi > Resto Schami > Heal Pala",},
{["loot_id"] = "40065", ["loot_name"] = "Fool´s Trial", ["prio"] = "Prio: Feral > Ret/Enhancer/Rogue",},
{["loot_id"] = "40069", ["loot_name"] = "Heritage", ["prio"] = "Prio: Protpala > Tanks",},
{["loot_id"] = "40064", ["loot_name"] = "Thunderstorm Amulet", ["prio"] = "Prio: Shadow > Caster",},
{["loot_id"] = "40378", ["loot_name"] = "Ceaseless Pity", ["prio"] = "Prio: Resto Schami > Diszi",},
{["loot_id"] = "40374", ["loot_name"] = "Cosmic Lights", ["prio"] = "Prio: Resto Schami > Boomkin/Shadow/Mage > Warlock",},
{["loot_id"] = "40369", ["loot_name"] = "Icy Blast Amulett", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "13385", ["loot_name"] = "Heroic Key to the Focusing Iris", ["prio"] = "Prio: Demo > DPS",},
{["loot_id"] = "40387", ["loot_name"] = "Boundless Ambition", ["prio"] = "Prio: Bear > DK > Prot Pala",},
{["loot_id"] = "39716", ["loot_name"] = "Shield of Assimilation", ["prio"] = "Prio: Resto Schami > Heal Pala > Ele",},
{["loot_id"] = "40266", ["loot_name"] = "Hero´s Surrender", ["prio"] = "Prio: Prot Pala",},
{["loot_id"] = "40401", ["loot_name"] = "Voice of Reason", ["prio"] = "Prio: Ele > Heal Pala > Resto Schami",},
{["loot_id"] = "40400", ["loot_name"] = "Wall of Terror", ["prio"] = "Prio: Prot Pala",},
{["loot_id"] = "39766", ["loot_name"] = "Matriarch´s Spawn", ["prio"] = "Prio: 1. Demo > Resto Druid > Arcane/Warlock",},
{["loot_id"] = "40273", ["loot_name"] = "Surplus Limb", ["prio"] = "Prio: Shadow/Mage/Affli/Boomkin > Demo > Ele",},
{["loot_id"] = "40192", ["loot_name"] = "Accursed Spine", ["prio"] = "Prio: Boomkin > Shadow/Affli > Diszi",},
{["loot_id"] = "40350", ["loot_name"] = "Urn of Lost Memories", ["prio"] = "Prio: Diszi > Boomkin",},
{["loot_id"] = "40265", ["loot_name"] = "Arrowsong", ["prio"] = "Prio: Hunter > DPS Warris > Rogue",},
{["loot_id"] = "40385", ["loot_name"] = "Envoy of Mortality", ["prio"] = "Prio: Hunter > Rogue > DPS Warris",},
{["loot_id"] = "40190", ["loot_name"] = "Spinning Fate", ["prio"] = "Prio: Arms > Fury > Rogue",},
{["loot_id"] = "39712", ["loot_name"] = "Gemmed Wand of the Nerubians", ["prio"] = "Prio: Mage/Shadow > Affli",},
{["loot_id"] = "40284", ["loot_name"] = "Plague Igniter", ["prio"] = "Prio: Caster",},
{["loot_id"] = "39757", ["loot_name"] = "Idol of Worship", ["prio"] = "Prio: Feral",},
{["loot_id"] = "40321", ["loot_name"] = "Idol of Shooting Star", ["prio"] = "Prio: ",},
{["loot_id"] = "40342", ["loot_name"] = "Idol if Awakening", ["prio"] = "Prio: ",},
{["loot_id"] = "40268", ["loot_name"] = "Libram of Tolerance", ["prio"] = "Prio: Holypala",},
{["loot_id"] = "40191", ["loot_name"] = "Libram of Radiance", ["prio"] = "Prio: ",},
{["loot_id"] = "40337", ["loot_name"] = "Libram of Resurgence", ["prio"] = "Prio: ",},
{["loot_id"] = "40207", ["loot_name"] = "Sigil of Arwareness", ["prio"] = "Prio: ",},
{["loot_id"] = "39728", ["loot_name"] = "Totem of Misery", ["prio"] = "Prio: Resto Schami",},
{["loot_id"] = "40267", ["loot_name"] = "Totem of Hex", ["prio"] = "Prio: Ele",},
{["loot_id"] = "40322", ["loot_name"] = "Totem of Dueling", ["prio"] = "Prio: ",},
{["loot_id"] = "40245", ["loot_name"] = "Fading Glow", ["prio"] = "Prio: Diszi",},
{["loot_id"] = "40335", ["loot_name"] = "Touch of Horror", ["prio"] = "Prio: ",},
{["loot_id"] = "40346", ["loot_name"] = "Final Voyage", ["prio"] = "Prio: Hunter > Rogue/DPS Warris",},
{["loot_id"] = "40080", ["loot_name"] = "Lost Jewel", ["prio"] = "Prio: 1. Demo > Boomkin/Shadow > Warlock > Rest",},
{["loot_id"] = "40075", ["loot_name"] = "Ruthlessness", ["prio"] = "Prio: Unholy > Frost/Ret > Fury > Arms",},
{["loot_id"] = "40107", ["loot_name"] = "Sand-Worn Band", ["prio"] = "Prio: Prot Pala > Blood > Feral Bear",},
{["loot_id"] = "40074", ["loot_name"] = "Strong Handed Ring", ["prio"] = "Prio: Rogue/Hunter/Enhancer > Feral > Rest",},
{["loot_id"] = "40108", ["loot_name"] = "Seized Beauty", ["prio"] = "Prio: Heal Pala/Resto Schami/Diszi > Resto Druid",},
{["loot_id"] = "40370", ["loot_name"] = "Gatekeeper", ["prio"] = "Prio: Feral Bear > Blood > Prot Pala",},
{["loot_id"] = "40375", ["loot_name"] = "Ring of Decaying Beauty", ["prio"] = "Prio: Resto Druid > Diszi > Heal Pala/Resto Schami",},
{["loot_id"] = "40399", ["loot_name"] = "Signet of Manifested Pain", ["prio"] = "Prio: Mage/Boomkin > Ele / Shadow / Affli",},
{["loot_id"] = "39719", ["loot_name"] = "Mantel of the Locusts", ["prio"] = "Prio: Resto Druid > Shadow",},
{["loot_id"] = "40286", ["loot_name"] = "Mantel of the Corrupted", ["prio"] = "Prio: Ele > Shadow",},
{["loot_id"] = "40351", ["loot_name"] = "Mantle of the Fatigued Sage", ["prio"] = "Prio: ",},
{["loot_id"] = "40289", ["loot_name"] = "Sympathetic Amice", ["prio"] = "Prio: Diszi > Resto Schami",},
{["loot_id"] = "40063", ["loot_name"] = "Mantle of Shattered Kinship", ["prio"] = "Prio: Resto Druid",},
{["loot_id"] = "40305", ["loot_name"] = "Spaulders of Egotism", ["prio"] = "Prio: Rogue > Feral",},
{["loot_id"] = "40288", ["loot_name"] = "Spaulders of Incoherence", ["prio"] = "Prio: Resto Schami > Heal Pala",},
{["loot_id"] = "40299", ["loot_name"] = "Pauldrons of the Abandoned", ["prio"] = "Prio: Enhancer > Hunter",},
{["loot_id"] = "40315", ["loot_name"] = "Shoulderpads of Secret Arts", ["prio"] = "Prio: Enhancer/Hunter",},
{["loot_id"] = "39704", ["loot_name"] = "Pauldrons of Unnatural Death", ["prio"] = "Prio: Blood > Prot Pala",},
{["loot_id"] = "39725", ["loot_name"] = "Epaulets of the Grieving Servant", ["prio"] = "Prio: Holy Pala",},
{["loot_id"] = "40185", ["loot_name"] = "Shoulderguards of Opportunity", ["prio"] = "Prio: Fury/Arms > Frost  > Ret/Unholy",},
{["loot_id"] = "40334", ["loot_name"] = "Burdened Shoulderplates", ["prio"] = "Prio: Prot Pala > Tanks",},
{["loot_id"] = "40377", ["loot_name"] = "Noble Birthright Pauldrons", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40257", ["loot_name"] = "Defender´s Code", ["prio"] = "Prio: Prot Pala/Blood > Feral Bear",},
{["loot_id"] = "40255", ["loot_name"] = "Dying Curse", ["prio"] = "Prio: 1. Demo > Boomkin > Shadow/Warlock/Ele > Enhancer",},
{["loot_id"] = "40258", ["loot_name"] = "Forethought Talisman", ["prio"] = "Prio: Holy Pala/Diszi > Healer",},
{["loot_id"] = "40256", ["loot_name"] = "Grim Toll", ["prio"] = "Prio: Arms > Fury > Feral Cat > Frost",},
{["loot_id"] = "40371", ["loot_name"] = "Bandit´s Insignia", ["prio"] = "Prio: ",},
{["loot_id"] = "40373", ["loot_name"] = "Extract of Necromantic Power", ["prio"] = "Prio: ",},
{["loot_id"] = "40372", ["loot_name"] = "Rune of Repulsion", ["prio"] = "Prio: Blood/Prot Pala",},
{["loot_id"] = "40382", ["loot_name"] = "Soul of the Dead", ["prio"] = "Prio: Resto Schami",},
{["loot_id"] = "39721", ["loot_name"] = "Shas of the Parior", ["prio"] = "Prio: Resto Shami > Diszi > Resto Druid",},
{["loot_id"] = "39735", ["loot_name"] = "Belt of False Dignity", ["prio"] = "Prio: ",},
{["loot_id"] = "40271", ["loot_name"] = "Shash of Solitude", ["prio"] = "Prio: Diszi > Resto Druid",},
{["loot_id"] = "40301", ["loot_name"] = "Cincture of Polarity", ["prio"] = "Prio: Ele > Boomkin > Shadow/Warlock/Arcane",},
{["loot_id"] = "40260", ["loot_name"] = "Belt of the Tortured", ["prio"] = "Prio: Rogues/Feral > Arms > Ret > Fury",},
{["loot_id"] = "40200", ["loot_name"] = "Belt of Potent Chanting", ["prio"] = "Prio: Boomkin",},
{["loot_id"] = "40205", ["loot_name"] = "Stalk-Skin Belt", ["prio"] = "Prio: Rogue/Feral > DPS Warri > Hunter/Enhancer",},
{["loot_id"] = "40341", ["loot_name"] = "Shackled Cinch", ["prio"] = "Prio: Resto Druid/Boomkin",},
{["loot_id"] = "39762", ["loot_name"] = "Torn Web Wrapping", ["prio"] = "Prio: Hunter > Enhancer > Arms > Ret > Fury",},
{["loot_id"] = "40272", ["loot_name"] = "Gridle of the Gambit", ["prio"] = "Prio: Resto Schami > Heal Pala",},
{["loot_id"] = "40275", ["loot_name"] = "Depraved Linked Belt", ["prio"] = "Prio: Hunter > Enhancer > Warri",},
{["loot_id"] = "40327", ["loot_name"] = "Gridle of Recuperiation", ["prio"] = "Prio: Resto Schami > Ele > Heal Pala",},
{["loot_id"] = "39759", ["loot_name"] = "Ablative Chitin Gridle", ["prio"] = "Prio: Maintank",},
{["loot_id"] = "40263", ["loot_name"] = "Fleshless Gridle", ["prio"] = "Prio: Prot Pala > Blood",},
{["loot_id"] = "40259", ["loot_name"] = "Waistguard of Divine Grave", ["prio"] = "Prio: Holypala",},
{["loot_id"] = "40278", ["loot_name"] = "Gridle of Chivaltry", ["prio"] = "Prio: Frost/Unholy/Ret",},
{["loot_id"] = "40241", ["loot_name"] = "Girdle of Unity", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40317", ["loot_name"] = "Gridle of Razuvious", ["prio"] = "Prio: Fury > Frost > Ret > Arms > Unholy",},
{["loot_id"] = "40402", ["loot_name"] = "Last Laugh", ["prio"] = "Prio: Prot Pala > Unholy > Blood",},
{["loot_id"] = "39714", ["loot_name"] = "Webbed Death", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "40281", ["loot_name"] = "Twilight Mist", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "40368", ["loot_name"] = "Murder", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "40386", ["loot_name"] = "Sinister Revenge", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "39763", ["loot_name"] = "Wraith Strike", ["prio"] = "Prio: Enhancer > Resto Schami/Ele/Resto Druid/Boomkin",},
{["loot_id"] = "40239", ["loot_name"] = "The Hand of Nerub", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "40383", ["loot_name"] = "Calamity´s Grasp", ["prio"] = "Prio: Rogue > Enhancer",},
{["loot_id"] = "40189", ["loot_name"] = "Angry Dread", ["prio"] = "Prio: Frost > Unholy DW > Enhancer",},
{["loot_id"] = "40244", ["loot_name"] = "The Impossible Dream", ["prio"] = "Prio: Boomkin / Diszi / Shadow > Rest",},
{["loot_id"] = "40395", ["loot_name"] = "Torch of Holy Fire", ["prio"] = "Prio: Ele/Boomkin/Shadow/Heal Pala/Resto Schami/Diszi",},
{["loot_id"] = "39730", ["loot_name"] = "Widow´s Fury", ["prio"] = "Prio: Unholy DW > Rogue",},
{["loot_id"] = "40336", ["loot_name"] = "Life and Death", ["prio"] = "Prio: Heal Pala/Mage > Warlock",},
{["loot_id"] = "40345", ["loot_name"] = "Broken Promise", ["prio"] = "Prio: Prot Pala > Blood",},
{["loot_id"] = "40396", ["loot_name"] = "The Turning Tide", ["prio"] = "Prio: 1. Demo > Mage/Warlock > Heal Pala",},
{["loot_id"] = "40384", ["loot_name"] = "Betrayer of Humanity", ["prio"] = "Prio: Arms > Fury > Ret > Unholy",},
{["loot_id"] = "39758", ["loot_name"] = "The Jawbone", ["prio"] = "Prio: 2h Unholy / Ret > Fury > Feral",},
{["loot_id"] = "40208", ["loot_name"] = "Cryptfiend´s Bite", ["prio"] = "Prio: Ret > Arms > Feral > Unholy > Hunter",},
{["loot_id"] = "40280", ["loot_name"] = "Origin of Nightmares", ["prio"] = "Prio: Feral",},
{["loot_id"] = "40300", ["loot_name"] = "Spire of Sunset", ["prio"] = "Prio: Resto Schami/Ele",},
{["loot_id"] = "40233", ["loot_name"] = "The Undeath Carrier", ["prio"] = "Prio: Feral > Hunter",},
{["loot_id"] = "40348", ["loot_name"] = "Damnation", ["prio"] = "Prio: Boomkin/Mage > Rest",},
{["loot_id"] = "40388", ["loot_name"] = "Journey´s End", ["prio"] = "Prio: Feral > Hunter",},
{["loot_id"] = "40343", ["loot_name"] = "Armageddon", ["prio"] = "Prio: Ret > Unholy > Fury > Arms",},
{["loot_id"] = "39731", ["loot_name"] = "Punctilious Binding", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "40198", ["loot_name"] = "Bands of Impurity", ["prio"] = "Prio: Boomkin",},
{["loot_id"] = "40325", ["loot_name"] = "Bindings of the Expansive Mind", ["prio"] = "Prio: DPS Casters > Healer",},
{["loot_id"] = "40338", ["loot_name"] = "Bindings of Yearning", ["prio"] = "Prio: Diszi > Resto Schami > Heal Pala/Resto Druid",},
{["loot_id"] = "39765", ["loot_name"] = "Sinner´s Bindings", ["prio"] = "Prio: Rogue > Feral > Fury > Arms > Hunter",},
{["loot_id"] = "40186", ["loot_name"] = "Thrusting Bands", ["prio"] = "Prio: Feral > Rogue > DPS-Warri/Ret",},
{["loot_id"] = "40323", ["loot_name"] = "Esteemed Bindings", ["prio"] = "Prio: Boomkin > Resto Druid",},
{["loot_id"] = "39702", ["loot_name"] = "Arachnoid Gold Band", ["prio"] = "Prio: Hunter/Enhancer",},
{["loot_id"] = "40282", ["loot_name"] = "Slime Stream Bands", ["prio"] = "Prio: Hunter > Enhancer > Arms",},
{["loot_id"] = "40209", ["loot_name"] = "Bindings of the Decrepit", ["prio"] = "Prio: Resto Schami > Heal Pala",},
{["loot_id"] = "40324", ["loot_name"] = "Bands of Mutual Respect", ["prio"] = "Prio: Ele > Rest Schami > Heal Pala",},
{["loot_id"] = "39729", ["loot_name"] = "Bracers of the Tyrant", ["prio"] = "Prio: Unholy > Frost/Ret > DPS Warri",},
{["loot_id"] = "39764", ["loot_name"] = "Bindings of the Hapless Prey", ["prio"] = "Prio: Prot Pala",},
{["loot_id"] = "40274", ["loot_name"] = "Bracers of Liberation", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40306", ["loot_name"] = "Bracers of the Unholy Knight", ["prio"] = "Prio: Blood > Prot Pala",},
{["loot_id"] = "40332", ["loot_name"] = "Abetment Bracers", ["prio"] = "Prio: Heal Pala",},
{["loot_id"] = "40330", ["loot_name"] = "Bracers of Unrelenting Attack", ["prio"] = "Prio: Arms/Ret > Unholy > Frost/Fury",},
{["loot_id"] = "40253", ["loot_name"] = "Shawl of the Old Maid", ["prio"] = "Prio: -",},
{["loot_id"] = "40251", ["loot_name"] = "Shroud of Luminosity", ["prio"] = "Prio: Resto Druid",},
{["loot_id"] = "40061", ["loot_name"] = "Quivering Tunic", ["prio"] = "Prio: Resto Schami",},
{["loot_id"] = "39767", ["loot_name"] = "Undiminished Battleplate", ["prio"] = "Prio: Ret > DKs > DPS Warris > Tanks",},
{["loot_id"] = "40270", ["loot_name"] = "Boots of Septic Wounds", ["prio"] = "Prio: Boomkin  >  Resto Druid",},
{["loot_id"] = "39732", ["loot_name"] = "Faerlina´s Madness", ["prio"] = "Prio: ",},
{["loot_id"] = "39768", ["loot_name"] = "Cowl of the Perished", ["prio"] = "Prio: -",},
{["loot_id"] = "40296", ["loot_name"] = "Cover of Silence", ["prio"] = "Prio: -",},
{["loot_id"] = "39723", ["loot_name"] = "Fire-Scorched Greathelm", ["prio"] = "Prio: -",},
{["loot_id"] = "39760", ["loot_name"] = "Helm of Diminished Pride", ["prio"] = "Prio: -",},
{["loot_id"] = "40264", ["loot_name"] = "Split Greathammer", ["prio"] = "Prio: -",},
{["loot_id"] = "39722", ["loot_name"] = "Swarm Bindings", ["prio"] = "Prio: Boomkin",},
{["loot_id"] = "44005", ["loot_name"] = "Pennant Cloak", ["prio"] = "Prio: Heal Pala > Resto Schami / Arcane",},
{["loot_id"] = "44002", ["loot_name"] = "The Sanctum´s Flowing Vestments", ["prio"] = "Prio: Resto Druid > Diszi / Shadow > Rest",},
{["loot_id"] = "40453", ["loot_name"] = "Chestplate of the Great Aspects", ["prio"] = "Prio: Holypala",},
{["loot_id"] = "44000", ["loot_name"] = "Dragonstorm Breastplate", ["prio"] = "Prio: Blood > Prot Pala",},
{["loot_id"] = "44007", ["loot_name"] = "Headpiece of Reconciliation", ["prio"] = "Prio: Resto Druid > Heal Pala > Ele / Boomkin",},
{["loot_id"] = "40451", ["loot_name"] = "Hyaline Helm of the Sniper", ["prio"] = "Prio: Hunter / Enhancer",},
{["loot_id"] = "44006", ["loot_name"] = "Obsidian Greathelm", ["prio"] = "Prio: Frost > Unholy/Ret > Fury > Arms",},
{["loot_id"] = "44011", ["loot_name"] = "Leggings of the Honored", ["prio"] = "Prio: Feral/Ret > Rogue > DPS Warri",},
{["loot_id"] = "40446", ["loot_name"] = "Dragon Brood Legguards", ["prio"] = "Prio: Blood / Prot Pala",},
{["loot_id"] = "40433", ["loot_name"] = "Wyrmrest Band", ["prio"] = "Prio: Resto Druid > Diszi > Heal Pala / Resto Schami",},
{["loot_id"] = "40437", ["loot_name"] = "Concealment Shoulderpads", ["prio"] = "Prio: Feral > Rogue",},
{["loot_id"] = "40439", ["loot_name"] = "Mantel of the Eternal Sentinel", ["prio"] = "Prio: Ele / Resto Schami > Boomkin",},
{["loot_id"] = "40438", ["loot_name"] = "Council Chamber Epaulets", ["prio"] = "Prio: Resto Schami",},
{["loot_id"] = "44003", ["loot_name"] = "Upstanding Spaulders", ["prio"] = "Prio: Hunter > Enhancer",},
{["loot_id"] = "40431", ["loot_name"] = "Fury of the Five Flights", ["prio"] = "Prio: Ret > Rogue / Hunter",},
{["loot_id"] = "40432", ["loot_name"] = "Illustration of the Dragon Soul", ["prio"] = "Prio: ",},
{["loot_id"] = "40455", ["loot_name"] = "Staff of Restraint", ["prio"] = "Prio: Mage > Boomkin > Rest",},
{["loot_id"] = "44008", ["loot_name"] = "Unsullied Cuffs", ["prio"] = "Prio: 1. Demo > Rest > Eule",},
{["loot_id"] = "44004", ["loot_name"] = "Bountiful Gauntlets", ["prio"] = "Prio: -",},
{["loot_id"] = "40625", ["loot_name"] = "Breastplate of the Lost Conqueror", ["prio"] = "Prio: 1. Demo >  Prot Pala / Warlock/Healpala/Ret > Shadow/Diszi",},
{["loot_id"] = "40626", ["loot_name"] = "Breastplate of the Lost Protecto", ["prio"] = "Prio: Resto Schami/Enhancer > Arms/Fury > Ele > Hunter",},
{["loot_id"] = "40627", ["loot_name"] = "Breastplate of the Lost Vanquisher", ["prio"] = "Prio: Boomkin/Frost > Arcane > Unholy > Bear/Blood > Cat/Rogue > Resto Druid",},
{["loot_id"] = "40628", ["loot_name"] = "Gauntlets of the Lost Conqueror", ["prio"] = "Prio: Warlock > Healpala > Diszi > Prot Pala >  Shadow >  Ret",},
{["loot_id"] = "40629", ["loot_name"] = "Gauntlets of the Lost Protector", ["prio"] = "Prio: Enhancer > Resto Schami > Hunter > Arms/Fury > Ele",},
{["loot_id"] = "40630", ["loot_name"] = "Gauntlets of the Lost Vanquisher", ["prio"] = "Prio: Boomkin/Frost > Rogue > Arcane > Bear/Blood > Resto Druid > Cat/Unholy",},
{["loot_id"] = "40631", ["loot_name"] = "Crown of the Lost Conqueror", ["prio"] = "Prio: Prot Pala  > Warlock > Ret > Heal Pala > Shadow/Diszi",},
{["loot_id"] = "40632", ["loot_name"] = "Crown of the Lost Protector", ["prio"] = "Prio: Arms/Resto Schami > Ele/Fury > Enhancer/Hunter",},
{["loot_id"] = "40633", ["loot_name"] = "Crown of the Lost Vanquisher", ["prio"] = "Prio: Boomkin > Cat/Rogue/Arcane > Blood > Unholy > Frost > Bear > Resto Druid",},
{["loot_id"] = "40634", ["loot_name"] = "Legplates of the Lost Conqueror", ["prio"] = "Prio: Heal Pala > Ret > Prot Pala/Diszi > Warlock > Shadow",},
{["loot_id"] = "40635", ["loot_name"] = "Legplates of the Lost Protector", ["prio"] = "Prio: Ehancer/Resto Schami > Fury/Arms > Hunter > Ele",},
{["loot_id"] = "40636", ["loot_name"] = "Legplates of the Lost Vanquisher", ["prio"] = "Prio: Frost > Rogue/Arcane > Unholy/Cat/Bear > Boomkin > Resto Druid",},
{["loot_id"] = "40637", ["loot_name"] = "Mantle of the Lost Conqueror", ["prio"] = "Prio: 1. Demo > ProtPala/Ret > Warlock > Healpala > Diszi/Shadow",},
{["loot_id"] = "40638", ["loot_name"] = "Mantle of the Lost Protector", ["prio"] = "Prio: Enhancerment/Resto Schami > Fury/Arms > Hunter > Ele",},
{["loot_id"] = "40639", ["loot_name"] = "Mantle of the Lost Vanquisher", ["prio"] = "Prio: Frost/Boomkin > Cat/Rogue/Arcane > Bear/Unholy > Blood > Resto Druid",},
{["loot_id"] = "45108", ["loot_name"] = "Mechanist's Bindings", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45109", ["loot_name"] = "Gloves of the Fiery Behemoth", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45107", ["loot_name"] = "Iron Riveted War Helm", ["prio"] = "Prio: UDK > FDK > Ret (!BOE!)",},
{["loot_id"] = "45106", ["loot_name"] = "Strength of the Automaton", ["prio"] = "Prio: Fury > FDK",},
{["loot_id"] = "45110", ["loot_name"] = "Titanguard", ["prio"] = "Prio: MT",},
{["loot_id"] = "45086", ["loot_name"] = "Rising Sun", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45134", ["loot_name"] = "Plated Leggings of Ruination", ["prio"] = "Prio: Ret, UDK > FDK",},
{["loot_id"] = "45132", ["loot_name"] = "Golden Saronite Dragon", ["prio"] = "Prio: Rogue > Enha",},
{["loot_id"] = "45162", ["loot_name"] = "Flamestalker Boots", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45164", ["loot_name"] = "Helm of the Furnace Master", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45161", ["loot_name"] = "Girdle of Embers", ["prio"] = "Prio: Fury > DK",},
{["loot_id"] = "45157", ["loot_name"] = "Cindershard Ring", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45169", ["loot_name"] = "Totem of the Dancing Flame", ["prio"] = "Prio: Enha",},
{["loot_id"] = "45165", ["loot_name"] = "Worldcarver", ["prio"] = "Prio: Ret > Fury",},
{["loot_id"] = "45138", ["loot_name"] = "Drape of the Drakerider", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45141", ["loot_name"] = "Proto-hide Leggings", ["prio"] = "Prio: Auction House (!BOE!)",},
{["loot_id"] = "45143", ["loot_name"] = "Saronite Mesh Legguards", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45510", ["loot_name"] = "Libram of Discord", ["prio"] = "Prio: Ret",},
{["loot_id"] = "45142", ["loot_name"] = "Remorse", ["prio"] = "Prio: UDK",},
{["loot_id"] = "45249", ["loot_name"] = "Brass-lined Boots", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45248", ["loot_name"] = "Clockwork Legplates", ["prio"] = "Prio: FDK > UDK",},
{["loot_id"] = "45250", ["loot_name"] = "Crazed Construct Ring", ["prio"] = "Prio: UDK",},
{["loot_id"] = "45254", ["loot_name"] = "Sigil of the Vengeful Heart", ["prio"] = "Prio: UDK",},
{["loot_id"] = "45246", ["loot_name"] = "Golem-Shard Sticker", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45256", ["loot_name"] = "Twisted Visage", ["prio"] = "Prio: Feral > Hunter",},
{["loot_id"] = "45444", ["loot_name"] = "Gloves of the Steady Hand", ["prio"] = "Prio: Hunter > All",},
{["loot_id"] = "45442", ["loot_name"] = "Sorthalis, Hammer of the Watchers", ["prio"] = "Prio: UDK > Tanks",},
{["loot_id"] = "45224", ["loot_name"] = "Drape of the Lithe", ["prio"] = "Prio: Enha > Rogue",},
{["loot_id"] = "45232", ["loot_name"] = "Runed Ironhide Boots", ["prio"] = "Prio: Fury > Rogue > Feral",},
{["loot_id"] = "45227", ["loot_name"] = "Iron-studded Mantle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45225", ["loot_name"] = "Steelbreaker's Embrace", ["prio"] = "Prio: UDK > FDK > Ret",},
{["loot_id"] = "45193", ["loot_name"] = "Insurmountable Fervor", ["prio"] = "Prio: Ret > UDK > FDK > Fury",},
{["loot_id"] = "45233", ["loot_name"] = "Stormrune Edge", ["prio"] = "Prio: Fury > Ret",},
{["loot_id"] = "45245", ["loot_name"] = "Shoulderpads of the Intruder", ["prio"] = "Prio: Feral > Rogue > Ret",},
{["loot_id"] = "45244", ["loot_name"] = "Greaves of Swift Vengeance", ["prio"] = "Prio: Hunter > Enha",},
{["loot_id"] = "45241", ["loot_name"] = "Belt of Colossal Rage", ["prio"] = "Prio: FDK > UDK > Ret",},
{["loot_id"] = "45265", ["loot_name"] = "Shoulderpads of the Monolith", ["prio"] = "Prio: Rogue > Feral",},
{["loot_id"] = "45264", ["loot_name"] = "Decimator's Armguards", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45263", ["loot_name"] = "Wrathstone", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45266", ["loot_name"] = "Malice", ["prio"] = "Prio: FDK, UDK",},
{["loot_id"] = "45261", ["loot_name"] = "Giant's Bane", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45611", ["loot_name"] = "Solar Bindings", ["prio"] = "Prio: Rogue > Fury, Feral",},
{["loot_id"] = "45610", ["loot_name"] = "Boundless Gaze", ["prio"] = "Prio: Enha, Hunter",},
{["loot_id"] = "45599", ["loot_name"] = "Sabatons of Lifeless Night", ["prio"] = "Prio: FDK, UDK > Fury > Ret",},
{["loot_id"] = "45609", ["loot_name"] = "Comet's Trail", ["prio"] = "Prio: Rogue, Enha > UH",},
{["loot_id"] = "45607", ["loot_name"] = "Fang of Oblivion", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45613", ["loot_name"] = "Dreambinder", ["prio"] = "Prio: Feral > Hunter",},
{["loot_id"] = "45570", ["loot_name"] = "Skyforge Crossbow", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45588", ["loot_name"] = "Drape of the Skyborn", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45608", ["loot_name"] = "Brann's Signet Ring", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45325", ["loot_name"] = "Gloves of the Stonereaper", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45320", ["loot_name"] = "Shoulderplates of the Eternal", ["prio"] = "Prio: UDK > FDK",},
{["loot_id"] = "45315", ["loot_name"] = "Stonerender", ["prio"] = "Prio: UDK",},
{["loot_id"] = "45327", ["loot_name"] = "Siren's Cry", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45453", ["loot_name"] = "Winter's Icy Embrace", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45454", ["loot_name"] = "Frost-bound Chain Bracers", ["prio"] = "Prio: Hunter > Shaman",},
{["loot_id"] = "45461", ["loot_name"] = "Drape of Icy Intent", ["prio"] = "Prio: Rogue > Enha > Feral",},
{["loot_id"] = "45459", ["loot_name"] = "Frigid Strength of Hodir", ["prio"] = "Prio: FDK > Fury > Ret",},
{["loot_id"] = "45467", ["loot_name"] = "Belt of the Betrayed", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45469", ["loot_name"] = "Sif's Promise", ["prio"] = "Prio: Fury > Ret",},
{["loot_id"] = "45463", ["loot_name"] = "Vulmir, the Northern Tempest", ["prio"] = "Prio: DPS DK",},
{["loot_id"] = "45473", ["loot_name"] = "Embrace of the Gladiator", ["prio"] = "Prio: Rogue, Feral > Hunter",},
{["loot_id"] = "45472", ["loot_name"] = "Warhelm of the Champion", ["prio"] = "Prio: DPS DK > Ret",},
{["loot_id"] = "45481", ["loot_name"] = "Gauntlets of Ruthless Reprisal", ["prio"] = "Prio: UDK",},
{["loot_id"] = "45480", ["loot_name"] = "Nymph Heart Charm", ["prio"] = "Prio: Auction House (!BOE!)",},
{["loot_id"] = "45484", ["loot_name"] = "Bladetwister", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45489", ["loot_name"] = "Insanity's Grip", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45491", ["loot_name"] = "Waistguard of the Creator", ["prio"] = "Prio: Rogue > Feral",},
{["loot_id"] = "45663", ["loot_name"] = "Armbands of Bedlam", ["prio"] = "Prio: DPS DK > Ret",},
{["loot_id"] = "45494", ["loot_name"] = "Delirium's Touch", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45504", ["loot_name"] = "Darkcore Leggings", ["prio"] = "Prio: Hunter > Shaman (!BOE!)",},
{["loot_id"] = "45501", ["loot_name"] = "Boots of the Underdweller", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45503", ["loot_name"] = "Metallic Loop of the Sufferer", ["prio"] = "Prio: Enha > Rogue",},
{["loot_id"] = "45509", ["loot_name"] = "Idol of the Corruptor", ["prio"] = "Prio: Feral",},
{["loot_id"] = "45498", ["loot_name"] = "Lotrafen, Spear of the Damned", ["prio"] = "Prio: Hunter > Feral",},
{["loot_id"] = "45517", ["loot_name"] = "Pendulum of Infinity", ["prio"] = "Prio: Hunter > Rogue, Enha > Feral",},
{["loot_id"] = "45516", ["loot_name"] = "Voldrethar, Dark Blade of Oblivion", ["prio"] = "Prio: Fury > Ret",},
{["loot_id"] = "45523", ["loot_name"] = "Garona's Guise", ["prio"] = "Prio: Feral, Rogue",},
{["loot_id"] = "45524", ["loot_name"] = "Chestguard of Insidious Intent", ["prio"] = "Prio: Hunter > Enha",},
{["loot_id"] = "45525", ["loot_name"] = "Godbane Signet", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45522", ["loot_name"] = "Blood of the Old God", ["prio"] = "Prio: Enha > Rogue",},
{["loot_id"] = "45521", ["loot_name"] = "Earthshaper", ["prio"] = "Prio: Ret > Warrior",},
{["loot_id"] = "45536", ["loot_name"] = "Legguards of Cunning Deception", ["prio"] = "Prio: Rogue, Feral > Hunter, Fury",},
{["loot_id"] = "45534", ["loot_name"] = "Seal of the Betrayed King", ["prio"] = "Prio: UDK, FDK > Ret > Fury",},
{["loot_id"] = "45533", ["loot_name"] = "Dark Edge of Depravity", ["prio"] = "Prio: Ret > Hunter",},
{["loot_id"] = "45547", ["loot_name"] = "Relic Hunter's Cord", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45543", ["loot_name"] = "Shoulders of Misfortune", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45540", ["loot_name"] = "Bladebearer's Signet", ["prio"] = "Prio: UDK",},
{["loot_id"] = "45605", ["loot_name"] = "Daschal's Bite", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45117", ["loot_name"] = "Constructor's Handwraps", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45119", ["loot_name"] = "Embrace of the Leviathan", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45118", ["loot_name"] = "Steamworker's Goggles", ["prio"] = "Prio: R-Schami > HPal > Ele",},
{["loot_id"] = "45116", ["loot_name"] = "Freya's Choker of Warding", ["prio"] = "Prio: Healer",},
{["loot_id"] = "45113", ["loot_name"] = "Glowing Ring of Reclamation", ["prio"] = "Prio: Healer > DPS",},
{["loot_id"] = "45115", ["loot_name"] = "Leviathan Fueling Manual", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45114", ["loot_name"] = "Steamcaller's Totem", ["prio"] = "Prio: R-Schami",},
{["loot_id"] = "45135", ["loot_name"] = "Boots of Fiery Resolution", ["prio"] = "Prio: Lock > Shadow > R-Druid ",},
{["loot_id"] = "45136", ["loot_name"] = "Shoulderpads of Dormant Energies", ["prio"] = "Prio: R-Druid, Boomy > Rest",},
{["loot_id"] = "45133", ["loot_name"] = "Pendant of Fiery Havoc", ["prio"] = "Prio: Lock > Boomy > Rest",},
{["loot_id"] = "45186", ["loot_name"] = "Soot-Covered Mantle", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45185", ["loot_name"] = "Flamewrought Cinch", ["prio"] = "Prio: R-Druid, Boomy > Rest",},
{["loot_id"] = "45187", ["loot_name"] = "Wristguards of the Firetender", ["prio"] = "Prio: R-Schami > Ele",},
{["loot_id"] = "45167", ["loot_name"] = "Lifeforge Breastplate", ["prio"] = "Prio: HPal > AH (!BOE!)",},
{["loot_id"] = "45168", ["loot_name"] = "Pyrelight Circle", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45171", ["loot_name"] = "Intensity", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45170", ["loot_name"] = "Scepter of Creation", ["prio"] = "Prio: Healer > DPS",},
{["loot_id"] = "45150", ["loot_name"] = "Collar of the Wyrmhunter", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45146", ["loot_name"] = "Shackles of the Odalisque", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45149", ["loot_name"] = "Bracers of the Broodmother", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45151", ["loot_name"] = "Belt of the Fallen Wyrm", ["prio"] = "Prio: Ele > Rest",},
{["loot_id"] = "45140", ["loot_name"] = "Razorscale Shoulderguards", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45148", ["loot_name"] = "Living Flame", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45147", ["loot_name"] = "Guiding Star", ["prio"] = "Prio: Healers > DPS",},
{["loot_id"] = "45253", ["loot_name"] = "Mantle of Wavering Calm", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45258", ["loot_name"] = "Sandals of Rash Temperament", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45260", ["loot_name"] = "Boots of Hasty Revival", ["prio"] = "Prio: R-Druid, Boomy > Rest",},
{["loot_id"] = "45259", ["loot_name"] = "Quartz-studded Harness", ["prio"] = "Prio: R-Druid > Rest",},
{["loot_id"] = "45252", ["loot_name"] = "Horologist's Wristguards", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45255", ["loot_name"] = "Thunderfall Totem", ["prio"] = "Prio: Ele",},
{["loot_id"] = "45257", ["loot_name"] = "Quartz Crystal Wand", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45446", ["loot_name"] = "Grasps of Reason", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45445", ["loot_name"] = "Breastplate of the Devoted", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45443", ["loot_name"] = "Charm of Meticulous Timing", ["prio"] = "Prio: HPal > Priest > R-Schami",},
{["loot_id"] = "45240", ["loot_name"] = "Raiments of the Iron Council", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45238", ["loot_name"] = "Overload Legwraps", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45237", ["loot_name"] = "Phaelia's Vestments of the Sprouting Seed", ["prio"] = "Prio: R-Druid > Boomy (!BOE!)",},
{["loot_id"] = "45239", ["loot_name"] = "Runeshaper's Gloves", ["prio"] = "Prio: R-Schami > Ele",},
{["loot_id"] = "45226", ["loot_name"] = "Ancient Iron Heaume", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45236", ["loot_name"] = "Unblinking Eye", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45235", ["loot_name"] = "Radiant Seal", ["prio"] = "Prio: Healer",},
{["loot_id"] = "45234", ["loot_name"] = "Rapture", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45242", ["loot_name"] = "Drape of Mortal Downfall", ["prio"] = "Prio: Mage > Boomy > Ele",},
{["loot_id"] = "45243", ["loot_name"] = "Sapphire Amulet of Renewal", ["prio"] = "Prio: Demo > Mage > R-Druid",},
{["loot_id"] = "45272", ["loot_name"] = "Robes of the Umbral Brute", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45275", ["loot_name"] = "Bracers of Unleashed Magic", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45273", ["loot_name"] = "Handwraps of Plentiful Recovery", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45274", ["loot_name"] = "Leggings of the Stoneweaver", ["prio"] = "Prio: R-Druid, Ele (!BOE!)",},
{["loot_id"] = "45269", ["loot_name"] = "Unfaltering Armguards", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45268", ["loot_name"] = "Gloves of the Pythonic Guardian", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45271", ["loot_name"] = "Ironmender", ["prio"] = "Prio: Caster DPS > Healers",},
{["loot_id"] = "45270", ["loot_name"] = "Idol of the Crying Wind", ["prio"] = "Prio: Boomy",},
{["loot_id"] = "45665", ["loot_name"] = "Pharos Gloves", ["prio"] = "Prio: Mage, Lock > Boomy, Shadow > Ele",},
{["loot_id"] = "45619", ["loot_name"] = "Starwatcher's Binding", ["prio"] = "Prio: Lock > Shadow > Mage > Boomy",},
{["loot_id"] = "45616", ["loot_name"] = "Star-beaded Clutch", ["prio"] = "Prio: Boomy > R-Druid",},
{["loot_id"] = "45615", ["loot_name"] = "Planewalker Treads", ["prio"] = "Prio: R-Schami > Rest",},
{["loot_id"] = "45620", ["loot_name"] = "Starshard Edge", ["prio"] = "Prio: Shadow > Boomy > Lock",},
{["loot_id"] = "45612", ["loot_name"] = "Constellus", ["prio"] = "Prio: Healpriest > Ele > Boomy",},
{["loot_id"] = "45617", ["loot_name"] = "Cosmos", ["prio"] = "Prio: Shadow > Boomy > Lock",},
{["loot_id"] = "45618", ["loot_name"] = "Sunglimmer Cloak", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45614", ["loot_name"] = "Starshine Circle", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45435", ["loot_name"] = "Cowl of the Absolute", ["prio"] = "Prio: Auction House (!BOE!)",},
{["loot_id"] = "45441", ["loot_name"] = "Sandals of the Ancient Keeper", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45439", ["loot_name"] = "Unwavering Stare", ["prio"] = "Prio: Boomy, R-Druid",},
{["loot_id"] = "45440", ["loot_name"] = "Amice of the Stoic Watch", ["prio"] = "Prio: R-Druid, Ele",},
{["loot_id"] = "45434", ["loot_name"] = "Greaves of the Rockmender", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45438", ["loot_name"] = "Ring of the Faithful Servant", ["prio"] = "Prio: Healer",},
{["loot_id"] = "45436", ["loot_name"] = "Libram of the Resolute", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45437", ["loot_name"] = "Runescribed Blade", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45452", ["loot_name"] = "Frostplate Greaves", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45451", ["loot_name"] = "Frozen Loop", ["prio"] = "Prio: Caster DPS",},
{["loot_id"] = "45462", ["loot_name"] = "Gloves of the Frozen Glade", ["prio"] = "Prio: Boomy > R-Druid > Rest",},
{["loot_id"] = "45460", ["loot_name"] = "Bindings of Winter Gale", ["prio"] = "Prio: Enha > Ele > R-Schami > HPal ",},
{["loot_id"] = "45457", ["loot_name"] = "Staff of Endless Winter", ["prio"] = "Prio: Mage > Lock > Boomy, Shadow",},
{["loot_id"] = "45468", ["loot_name"] = "Leggings of Lost Love", ["prio"] = "Prio: Caster, Healer (!BOE!)",},
{["loot_id"] = "45466", ["loot_name"] = "Scale of Fates", ["prio"] = "Prio: Aff > Boomy, Shadow > Fire",},
{["loot_id"] = "45474", ["loot_name"] = "Pauldrons of the Combatant", ["prio"] = "Prio: Ele, R-Druid > Rest",},
{["loot_id"] = "45470", ["loot_name"] = "Wisdom's Hold", ["prio"] = "Prio: Ele > HPal > R-Schami",},
{["loot_id"] = "45483", ["loot_name"] = "Boots of the Servant", ["prio"] = "Prio: Caster, Healer",},
{["loot_id"] = "45482", ["loot_name"] = "Leggings of the Lifetender", ["prio"] = "Prio: R-Druid, Boomy",},
{["loot_id"] = "45479", ["loot_name"] = "The Lifebinder", ["prio"] = "Prio: Caster, Healer",},
{["loot_id"] = "45486", ["loot_name"] = "Drape of the Sullen Goddess", ["prio"] = "Prio: Healpriest > Paladin",},
{["loot_id"] = "45488", ["loot_name"] = "Leggings of the Enslaved Idol", ["prio"] = "Prio: Shadow > Caster DPS",},
{["loot_id"] = "45493", ["loot_name"] = "Asimov's Drape", ["prio"] = "Prio: Caster, Healer (!BOE!)",},
{["loot_id"] = "45492", ["loot_name"] = "Malleable Steelweave Mantle", ["prio"] = "Prio: R-Druid, Boomy",},
{["loot_id"] = "45490", ["loot_name"] = "Pandora's Plea", ["prio"] = "Prio: R-Schami > Healers",},
{["loot_id"] = "45497", ["loot_name"] = "Crown of Luminescence", ["prio"] = "Prio: Lock, Boomy > Rest",},
{["loot_id"] = "45495", ["loot_name"] = "Conductive Seal", ["prio"] = "Prio: Lock > Caster DPS > Healers",},
{["loot_id"] = "45514", ["loot_name"] = "Mantle of the Unknowing", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45508", ["loot_name"] = "Belt of the Darkspeaker", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45512", ["loot_name"] = "Grips of the Unbroken", ["prio"] = "Prio: R-Druid, Boomy",},
{["loot_id"] = "45513", ["loot_name"] = "Boots of the Forgotten Depths", ["prio"] = "Prio: RSchami, Ele",},
{["loot_id"] = "45505", ["loot_name"] = "Belt of Clinging Hope", ["prio"] = "Prio: HPal ",},
{["loot_id"] = "45515", ["loot_name"] = "Ring of the Vacant Eye", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45511", ["loot_name"] = "Scepter of Lost Souls", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45520", ["loot_name"] = "Handwraps of the Vigilant", ["prio"] = "Prio: Healpriest > Caster DPS > Healer",},
{["loot_id"] = "45519", ["loot_name"] = "Vestments of the Blind Denizen", ["prio"] = "Prio: R-Druid > Boomy",},
{["loot_id"] = "45518", ["loot_name"] = "Flare of the Heavens", ["prio"] = "Prio: Lock, Mage > Boomy, Shadow, Ele",},
{["loot_id"] = "45529", ["loot_name"] = "Shawl of Haunted Memories", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45532", ["loot_name"] = "Cowl of Dark Whispers", ["prio"] = "Prio: FFA",},
{["loot_id"] = "45531", ["loot_name"] = "Chestguard of the Fallen God", ["prio"] = "Prio: Ele > R-Schami",},
{["loot_id"] = "45530", ["loot_name"] = "Sanity's Bond", ["prio"] = "Prio: Healer > Caster DPS",},
{["loot_id"] = "45527", ["loot_name"] = "Soulscribe", ["prio"] = "Prio: Healer > Caster DPS",},
{["loot_id"] = "45537", ["loot_name"] = "Treads of the False Oracle", ["prio"] = "Prio: Fire > Boomy > Ele > Rest",},
{["loot_id"] = "45535", ["loot_name"] = "Show of Faith", ["prio"] = "Prio: Priest > R-Druid > R-Schami",},
{["loot_id"] = "45541", ["loot_name"] = "Shroud of Alteration", ["prio"] = "Prio: Healers > Caster DPS",},
{["loot_id"] = "45549", ["loot_name"] = "Grips of Chaos", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45548", ["loot_name"] = "Belt of the Sleeper", ["prio"] = "Prio: R-Druid, Boomy",},
{["loot_id"] = "45544", ["loot_name"] = "Leggings of the Tortured Earth", ["prio"] = "Prio: Ele, R-Schami",},
{["loot_id"] = "45539", ["loot_name"] = "Pendant of Focused Energies", ["prio"] = "Prio: Caster DPS > Healer",},
{["loot_id"] = "45158", ["loot_name"] = "Heart of Iron", ["prio"] = "Prio: Maintank",},
{["loot_id"] = "45139", ["loot_name"] = "Dragonslayer's Brace", ["prio"] = "Prio: ProtW",},
{["loot_id"] = "45442", ["loot_name"] = "Sorthalis, Hammer of the Watchers", ["prio"] = "Prio: Blood > Warr",},
{["loot_id"] = "45587", ["loot_name"] = "Bulwark of Algalon", ["prio"] = "Prio: ProtP > Warr",},
{["loot_id"] = "45326", ["loot_name"] = "Platinum Band of the Aesir", ["prio"] = "Prio: ProtP",},
{["loot_id"] = "45471", ["loot_name"] = "Fate's Clutch", ["prio"] = "Prio: MT",},
{["loot_id"] = "45487", ["loot_name"] = "Handguards of Revitalization", ["prio"] = "Prio: MT",},
{["loot_id"] = "45485", ["loot_name"] = "Bronze Pendant of the Vanir", ["prio"] = "Prio: MT",},
{["loot_id"] = "45496", ["loot_name"] = "Titanskin Cloak", ["prio"] = "Prio: MT",},
{["loot_id"] = "45502", ["loot_name"] = "Helm of the Faceless", ["prio"] = "Prio: ProtW",},
{["loot_id"] = "45632", ["loot_name"] = "Breastplate of the Wayward Conqueror", ["prio"] = "Prio: Diszi > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45633", ["loot_name"] = "Breastplate of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45634", ["loot_name"] = "Breastplate of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45638", ["loot_name"] = "Crown of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45639", ["loot_name"] = "Crown of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45640", ["loot_name"] = "Crown of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45653", ["loot_name"] = "Legplates of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45654", ["loot_name"] = "Legplates of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45655", ["loot_name"] = "Legplates of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45641", ["loot_name"] = "Gauntlets of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45642", ["loot_name"] = "Gauntlets of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45643", ["loot_name"] = "Gauntlets of the Wayward Vanquisher", ["prio"] = "Prio: R-Druid, > Boomy, Mage, FDK > Rest",},
{["loot_id"] = "45656", ["loot_name"] = "Mantle of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45657", ["loot_name"] = "Mantle of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45658", ["loot_name"] = "Mantle of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45935", ["loot_name"] = "Ironbark Faceguard", ["prio"] = "Prio: ProtW > other Tanks",},
{["loot_id"] = "46014", ["loot_name"] = "Saronite Animus Cloak", ["prio"] = "Prio: ProtW > other Tanks",},
{["loot_id"] = "46039", ["loot_name"] = "Breastplate of the Timeless", ["prio"] = "Prio: ProtP > other Tanks",},
{["loot_id"] = "45283", ["loot_name"] = "Flamewatch Armguards", ["prio"] = "Prio: ",},
{["loot_id"] = "45304", ["loot_name"] = "Stormtempered Girdle", ["prio"] = "Prio: BDK > other Tanks",},
{["loot_id"] = "45295", ["loot_name"] = "Gilded Steel Legplates", ["prio"] = "Prio: BDK, ProtP > ProtW",},
{["loot_id"] = "45988", ["loot_name"] = "Greaves of the Iron Army", ["prio"] = "Prio: ",},
{["loot_id"] = "45696", ["loot_name"] = "Mark of the Unyielding", ["prio"] = "Prio: BDK > Tanks",},
{["loot_id"] = "46021", ["loot_name"] = "Royal Seal of King Llane", ["prio"] = "Prio: BDK, ProtW > ProtP",},
{["loot_id"] = "46067", ["loot_name"] = "Hammer of Crushing Whispers", ["prio"] = "Prio: BDK, ProtW",},
{["loot_id"] = "45876", ["loot_name"] = "Shiver", ["prio"] = "Prio: BDK",},
{["loot_id"] = "45947", ["loot_name"] = "Serilas, Blood Blade of Invar One-Arm", ["prio"] = "Prio: ProtP > Rogue",},
{["loot_id"] = "46097", ["loot_name"] = "Caress of Insanity", ["prio"] = "Prio: ProtP",},
{["loot_id"] = "45877", ["loot_name"] = "The Boreal Guard", ["prio"] = "Prio: ProtW > PPal",},
{["loot_id"] = "45697", ["loot_name"] = "Shoulderguards of the Solemn Watch", ["prio"] = "Prio: ProtW",},
{["loot_id"] = "45864", ["loot_name"] = "Cover of the Keepers", ["prio"] = "Prio: R-Druid > Boomy",},
{["loot_id"] = "45289", ["loot_name"] = "Lifespark Visage", ["prio"] = "Prio: Lock > R-Druid",},
{["loot_id"] = "46068", ["loot_name"] = "Amice of Inconceivable Horror", ["prio"] = "Prio: Lock, Shadow > Heal > Rest",},
{["loot_id"] = "46321", ["loot_name"] = "Sunglimmer Drape", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45317", ["loot_name"] = "Shawl of the Caretaker", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "45548", ["loot_name"] = "Belt of the Sleeper", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "46049", ["loot_name"] = "Zodiac Leggings", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "45378", ["loot_name"] = "Boots of the Petrified Forest", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "45447", ["loot_name"] = "Watchful Eye of Fate", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "45946", ["loot_name"] = "Fire Orchid Signet", ["prio"] = "Prio: Heal > DPS",},
{["loot_id"] = "45418", ["loot_name"] = "Lady Maye's Sapphire Ring", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "45703", ["loot_name"] = "Spark of Hope", ["prio"] = "Prio: R-Druid > Healpriest",},
{["loot_id"] = "45929", ["loot_name"] = "Sif's Remembrance", ["prio"] = "Prio: R-Druid > any Priest, R-Scham",},
{["loot_id"] = "46051", ["loot_name"] = "Meteorite Crystal", ["prio"] = "Prio: HPal > Healpriest > R-Druid",},
{["loot_id"] = "46035", ["loot_name"] = "Aesuga, Hand of the Ardent Champion", ["prio"] = "Prio: Heal > DPS",},
{["loot_id"] = "45332", ["loot_name"] = "Stormtip", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "45886", ["loot_name"] = "Icecore Staff", ["prio"] = "Prio: R-Druid",},
{["loot_id"] = "45867", ["loot_name"] = "Breastplate of the Stoneshaper", ["prio"] = "Prio: HPal > Ele",},
{["loot_id"] = "45943", ["loot_name"] = "Gloves of Whispering Winds", ["prio"] = "Prio: Ele > HPal",},
{["loot_id"] = "45933", ["loot_name"] = "Pendant of the Shallow Grave", ["prio"] = "Prio: Ele > HPal, Boomy",},
{["loot_id"] = "46046", ["loot_name"] = "Nebula Band", ["prio"] = "Prio: DPS > R-Schami",},
{["loot_id"] = "46323", ["loot_name"] = "Starshine Signet", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45887", ["loot_name"] = "Ice Layered Barrier", ["prio"] = "Prio: Heal > Ele",},
{["loot_id"] = "45682", ["loot_name"] = "Pulsing Spellshield", ["prio"] = "Prio: Heal > Ele",},
{["loot_id"] = "46341", ["loot_name"] = "Drape of the Spellweaver", ["prio"] = "Prio: R-Schami",},
{["loot_id"] = "45867", ["loot_name"] = "Breastplate of the Stoneshaper", ["prio"] = "Prio: R-Schami",},
{["loot_id"] = "45316", ["loot_name"] = "Armbraces of the Vibrant Flame", ["prio"] = "Prio: R-Schami (!BOE!)",},
{["loot_id"] = "45943", ["loot_name"] = "Gloves of Whispering Winds", ["prio"] = "Prio: R-Schami",},
{["loot_id"] = "46047", ["loot_name"] = "Pendant of the Somber Witness", ["prio"] = "Prio: R-Schami",},
{["loot_id"] = "45308", ["loot_name"] = "Eye of the Broodmother", ["prio"] = "Prio: Mage > Heal-Priest",},
{["loot_id"] = "46034", ["loot_name"] = "Leggings of Profound Darkness", ["prio"] = "Prio: Lock > any Priest",},
{["loot_id"] = "46050", ["loot_name"] = "Starlight Treads", ["prio"] = "Prio: any Priest > Lock, Boomy",},
{["loot_id"] = "46096", ["loot_name"] = "Signet of Soft Lament", ["prio"] = "Prio: Healpriest > Shadow",},
{["loot_id"] = "45314", ["loot_name"] = "Igniter Rod", ["prio"] = "Prio: Healpriest",},
{["loot_id"] = "45294", ["loot_name"] = "Petrified Ivy Sprig", ["prio"] = "Prio: Shadow > Lock > Mage > Priest",},
{["loot_id"] = "45713", ["loot_name"] = "Nurturing Touch", ["prio"] = "Prio: Lock, Healpriest",},
{["loot_id"] = "46042", ["loot_name"] = "Drape of the Messenger", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "46045", ["loot_name"] = "Pulsar Gloves", ["prio"] = "Prio: Shadow > Mage",},
{["loot_id"] = "45297", ["loot_name"] = "Shimmering Seal", ["prio"] = "Prio: Mage, Shadow",},
{["loot_id"] = "45990", ["loot_name"] = "Fusion Blade", ["prio"] = "Prio: Lock > Mage",},
{["loot_id"] = "45886", ["loot_name"] = "Icecore Staff", ["prio"] = "Prio: Shadow > Lock",},
{["loot_id"] = "46009", ["loot_name"] = "Bindings of the Depths", ["prio"] = "Prio: Boomy (!BOE!)",},
{["loot_id"] = "45293", ["loot_name"] = "Handguards of Potent Cures", ["prio"] = "Prio: Boomy",},
{["loot_id"] = "45455", ["loot_name"] = "Belt of the Crystal Tree", ["prio"] = "Prio: Boomy",},
{["loot_id"] = "45832", ["loot_name"] = "Mantle of the Preserver", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "46012", ["loot_name"] = "Vestments of the Piercing Light", ["prio"] = "Prio: Lock > Shadow",},
{["loot_id"] = "45291", ["loot_name"] = "Combustion Bracers", ["prio"] = "Prio: Shadow (!BOE!)",},
{["loot_id"] = "45423", ["loot_name"] = "Runetouch Wristwraps", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "45927", ["loot_name"] = "Handwraps of Resonance", ["prio"] = "Prio: Shadow (!BOE!)",},
{["loot_id"] = "45976", ["loot_name"] = "Static Charge Handwraps", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "45306", ["loot_name"] = "Binding of the Dragon Matriarch", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "45694", ["loot_name"] = "Conductive Cord", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "45894", ["loot_name"] = "Leggings of Unstable Discharge", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "46030", ["loot_name"] = "Treads of the Dragon Council", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "46312", ["loot_name"] = "Vanquished Clutches of Yogg-Saron", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "46013", ["loot_name"] = "Underworld Mantle", ["prio"] = "Prio: Lock",},
{["loot_id"] = "46037", ["loot_name"] = "Shoulderplates of the Celestial Watch", ["prio"] = "Prio: Fury > FDK > UDK",},
{["loot_id"] = "46032", ["loot_name"] = "Drape of the Faceless General", ["prio"] = "Prio: any > Enha > UDK",},
{["loot_id"] = "46320", ["loot_name"] = "Drape of the Skyherald", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45712", ["loot_name"] = "Chestplate of Titanic Fury", ["prio"] = "Prio: DPS DK",},
{["loot_id"] = "45888", ["loot_name"] = "Bitter Cold Armguards", ["prio"] = "Prio: DPS DK > Ret > Fury",},
{["loot_id"] = "46041", ["loot_name"] = "Starfall Girdle", ["prio"] = "Prio: any > Ret",},
{["loot_id"] = "45982", ["loot_name"] = "Fused Alloy Legplates", ["prio"] = "Prio: DPS DK",},
{["loot_id"] = "45330", ["loot_name"] = "Greaves of Iron Intensity", ["prio"] = "Prio: DPS DK",},
{["loot_id"] = "46040", ["loot_name"] = "Strength of the Heavens", ["prio"] = "Prio: UDK > Ret > FDK",},
{["loot_id"] = "45931", ["loot_name"] = "Mjolnir Runestone", ["prio"] = "Prio: FDK, Feral, Rogue, Fury > Enha > Hunter",},
{["loot_id"] = "46038", ["loot_name"] = "Dark Matter", ["prio"] = "Prio: Rogue, Enha > Hunter",},
{["loot_id"] = "45286", ["loot_name"] = "Pyrite Infuser", ["prio"] = "Prio: Rogue, Ret > FDK, UDK",},
{["loot_id"] = "46097", ["loot_name"] = "Caress of Insanity", ["prio"] = "Prio: FDK, UDK > Enha",},
{["loot_id"] = "45947", ["loot_name"] = "Serilas, Blood Blade of Invar One-Arm", ["prio"] = "Prio: FDK, UDK",},
{["loot_id"] = "45298", ["loot_name"] = "Razorscale Talon", ["prio"] = "Prio: Rogue > FDK, UDK",},
{["loot_id"] = "45318", ["loot_name"] = "Drape of Fuming Anger", ["prio"] = "Prio: UDK",},
{["loot_id"] = "46036", ["loot_name"] = "Void Sabre", ["prio"] = "Prio: UDK > Rogue",},
{["loot_id"] = "45993", ["loot_name"] = "Mimiron's Flight Goggles", ["prio"] = "Prio: Feral, Rogue > Ret > Hunter",},
{["loot_id"] = "45893", ["loot_name"] = "Guise of the Midgard Serpent", ["prio"] = "Prio: Feral, Rogue",},
{["loot_id"] = "45677", ["loot_name"] = "Treacherous Shoulderpads", ["prio"] = "Prio: Feral, Rogue",},
{["loot_id"] = "45704", ["loot_name"] = "Shawl of the Shattered Giant", ["prio"] = "Prio: Rogue, Hunter > Feral (!BOE!)",},
{["loot_id"] = "45940", ["loot_name"] = "Tunic of the Limber Stalker", ["prio"] = "Prio: Feral > Hunter",},
{["loot_id"] = "45869", ["loot_name"] = "Fluxing Energy Coils", ["prio"] = "Prio: Feral > Rogue, Hunter > Enha",},
{["loot_id"] = "46043", ["loot_name"] = "Gloves of the Endless Dark", ["prio"] = "Prio: Feral, Rogue > Hunter",},
{["loot_id"] = "46095", ["loot_name"] = "Soul-Devouring Cinch", ["prio"] = "Prio: Feral, Rogue > Fury, Hunter > Ret",},
{["loot_id"] = "45709", ["loot_name"] = "Nimble Climber's Belt", ["prio"] = "Prio: Rogue > Feral (!BOE!)",},
{["loot_id"] = "45945", ["loot_name"] = "Seed of Budding Carnage", ["prio"] = "Prio: Feral > Rogue > Hunter",},
{["loot_id"] = "46048", ["loot_name"] = "Band of Lights", ["prio"] = "Prio: Feral, Rogue > Ret > Rest",},
{["loot_id"] = "46322", ["loot_name"] = "Brann's Sealing Ring", ["prio"] = "Prio: Q-Item",},
{["loot_id"] = "45456", ["loot_name"] = "Loop of the Agile", ["prio"] = "Prio: Enha",},
{["loot_id"] = "46033", ["loot_name"] = "Tortured Earth", ["prio"] = "Prio: Feral",},
{["loot_id"] = "46067", ["loot_name"] = "Hammer of Crushing Whispers", ["prio"] = "Prio: Fury, Ret > Feral",},
{["loot_id"] = "45329", ["loot_name"] = "Circlet of True Sight", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45300", ["loot_name"] = "Mantle of Fiery Vengeance", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45873", ["loot_name"] = "Winter's Frigid Embrace", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45941", ["loot_name"] = "Chestguard of the Lasher", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45301", ["loot_name"] = "Bracers of the Smothering Inferno", ["prio"] = "Prio: Hunter (!BOE!)",},
{["loot_id"] = "45989", ["loot_name"] = "Tempered Mercury Greaves", ["prio"] = "Prio: Enha > Hunter",},
{["loot_id"] = "46008", ["loot_name"] = "Choker of the Abyss", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "45870", ["loot_name"] = "Magnetized Projectile Emitter", ["prio"] = "Prio: Hunter > Rest",},
{["loot_id"] = "46010", ["loot_name"] = "Darkstone Ring", ["prio"] = "Prio: Ret",},
{["loot_id"] = "45868", ["loot_name"] = "Aesir's Edge", ["prio"] = "Prio: Fury, Ret ",},
{["loot_id"] = "45449", ["loot_name"] = "The Masticator", ["prio"] = "Prio: Rogue, Enha",},
{["loot_id"] = "45930", ["loot_name"] = "Combatant's Bootblade", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45331", ["loot_name"] = "Rune-Etched Nightblade", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "46024", ["loot_name"] = "Kingsbane", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45142", ["loot_name"] = "Remorse", ["prio"] = "Prio: Rogue",},
{["loot_id"] = "45296", ["loot_name"] = "Twirling Blades", ["prio"] = "Prio: Rogue, Fury",},
{["loot_id"] = "46018", ["loot_name"] = "Deliverance", ["prio"] = "Prio: Hunter > Rogue",},
{["loot_id"] = "45973", ["loot_name"] = "Stylish Power Cape", ["prio"] = "Prio: Fury",},
{["loot_id"] = "45650", ["loot_name"] = "Leggings of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45651", ["loot_name"] = "Leggings of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45652", ["loot_name"] = "Leggings of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45659", ["loot_name"] = "Spaulders of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45660", ["loot_name"] = "Spaulders of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45661", ["loot_name"] = "Spaulders of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45644", ["loot_name"] = "Gloves of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45645", ["loot_name"] = "Gloves of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45646", ["loot_name"] = "Gloves of the Wayward Vanquisher", ["prio"] = "Prio: R-Druid, > Boomy, Mage, FDK > Rest",},
{["loot_id"] = "45647", ["loot_name"] = "Helm of the Wayward Conqueror", ["prio"] = "Prio: Diszi , HPal > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45648", ["loot_name"] = "Helm of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45649", ["loot_name"] = "Helm of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "45635", ["loot_name"] = "Chestguard of the Wayward Conqueror", ["prio"] = "Prio: Diszi > Ret, Lock, Shadow > Rest",},
{["loot_id"] = "45636", ["loot_name"] = "Chestguard of the Wayward Protector", ["prio"] = "Prio: Shaman > Warrior > Hunter",},
{["loot_id"] = "45637", ["loot_name"] = "Chestguard of the Wayward Vanquisher", ["prio"] = "Prio: Mage, R-Druid, > Boomy, FDK > Rest",},
{["loot_id"] = "46052", ["loot_name"] = "Reply-Code Alpha", ["prio"] = "Prio: DPS > Heal",},
{["loot_id"] = "46053", ["loot_name"] = "Reply-Code Alpha", ["prio"] = "Prio: Heal > DPS",},
{["loot_id"] = "45038", ["loot_name"] = "Fragment of Val'anyr", ["prio"] = "Prio: special",},
{["loot_id"] = "45087", ["loot_name"] = "Runed Orb", ["prio"] = "Prio: Bank",},
{["loot_id"] = "45450", ["loot_name"] = "Northern Barrier", ["prio"] = "Prio: ProtW > PPal (!BOE!)",},
{["loot_id"] = "45247", ["loot_name"] = "Signet of the Earthshaker", ["prio"] = "Prio: ProtW > AH (!BOE!) > Rest",},
{["loot_id"] = "45322", ["loot_name"] = "Cloak of the Iron Council", ["prio"] = "Prio: Auction House (!BOE!)",},
{["loot_id"] = "45874", ["loot_name"] = "Signet of Winter", ["prio"] = "Prio: Tanks > AH (!BOE!)",},
{["loot_id"] = "45975", ["loot_name"] = "Cable of the Metrognome", ["prio"] = "Prio: Auction House (!BOE!)",},
{["loot_id"] = "45680", ["loot_name"] = "Armbands of the Construct", ["prio"] = "Prio: Auction House (!BOE!)",},
----- TEST
{["loot_id"] = "50709", ["loot_name"] = "Bryntroll, the Bone Arbiter", ["prio"] = "Ret,BDK > Fury",},
{["loot_id"] = "50415", ["loot_name"] = "Bryntroll, the Bone Arbiter", ["prio"] = "Ret,BDK > Fury",},
{["loot_id"] = "50613", ["loot_name"] = "Crushing Coldwraith Belt", ["prio"] = "Mage,Lock,Shadow > Ele,Boomy > Healer",},
{["loot_id"] = "49978", ["loot_name"] = "Crushing Coldwraith Belt", ["prio"] = "Mage,Lock,Shadow > Ele,Boomy > Healer",},
{["loot_id"] = "50608", ["loot_name"] = "Frozen Bonespike", ["prio"] = "Disc",},
{["loot_id"] = "49968", ["loot_name"] = "Frozen Bonespike", ["prio"] = "Disc",},
{["loot_id"] = "50607", ["loot_name"] = "Frostbitten Fur Boots", ["prio"] = "Feral > Rogue,Ret,MM > SV",},
{["loot_id"] = "49950", ["loot_name"] = "Frostbitten Fur Boots", ["prio"] = "Feral > Rogue,Ret,MM > SV",},
{["loot_id"] = "50615", ["loot_name"] = "Handguards of Winter's Respite", ["prio"] = "FFA",},
{["loot_id"] = "49979", ["loot_name"] = "Handguards of Winter's Respite", ["prio"] = "FFA",},
{["loot_id"] = "50605", ["loot_name"] = "Snowserpent Mail Helm", ["prio"] = "Enha",},
{["loot_id"] = "49952", ["loot_name"] = "Snowserpent Mail Helm", ["prio"] = "Enha",},
{["loot_id"] = "50606", ["loot_name"] = "Gendarme's Cuirass", ["prio"] = "FFA",},
{["loot_id"] = "49951", ["loot_name"] = "Gendarme's Cuirass", ["prio"] = "FFA",},
{["loot_id"] = "50612", ["loot_name"] = "Legguards of Lost Hope", ["prio"] = "LK Tank",},
{["loot_id"] = "49964", ["loot_name"] = "Legguards of Lost Hope", ["prio"] = "LK Tank",},
{["loot_id"] = "50617", ["loot_name"] = "Rusted Bonespike Pauldrons", ["prio"] = "HolyPal",},
{["loot_id"] = "49980", ["loot_name"] = "Rusted Bonespike Pauldrons", ["prio"] = "HolyPal",},
{["loot_id"] = "50611", ["loot_name"] = "Bracers of Dark Reckoning", ["prio"] = "LK Tank",},
{["loot_id"] = "49960", ["loot_name"] = "Bracers of Dark Reckoning", ["prio"] = "LK Tank",},
{["loot_id"] = "50616", ["loot_name"] = "Bulwark of Smouldering Steel", ["prio"] = "Ele > HolyPal, RestoS",},
{["loot_id"] = "49976", ["loot_name"] = "Bulwark of Smouldering Steel", ["prio"] = "Ele > HolyPal, RestoS",},
{["loot_id"] = "50604", ["loot_name"] = "Band of the Bone Colossus", ["prio"] = "Enha,Assa > Feral,Ret",},
{["loot_id"] = "49949", ["loot_name"] = "Band of the Bone Colossus", ["prio"] = "Enha,Assa > Feral,Ret",},
{["loot_id"] = "50610", ["loot_name"] = "Marrowgar's Frigid Eye", ["prio"] = "Healer > Disc",},
{["loot_id"] = "49967", ["loot_name"] = "Marrowgar's Frigid Eye", ["prio"] = "Healer > Disc",},
{["loot_id"] = "50614", ["loot_name"] = "Loop of the Endless Labyrinth", ["prio"] = "Boomy,Mage",},
{["loot_id"] = "49977", ["loot_name"] = "Loop of the Endless Labyrinth", ["prio"] = "Boomy,Mage",},
{["loot_id"] = "50609", ["loot_name"] = "Bone Sentinel's Amulet", ["prio"] = "RestoD",},
{["loot_id"] = "49975", ["loot_name"] = "Bone Sentinel's Amulet", ["prio"] = "RestoD",},
{["loot_id"] = "50638", ["loot_name"] = "Zod's Repeating Longbow", ["prio"] = "Hunter",},
{["loot_id"] = "50034", ["loot_name"] = "Zod's Repeating Longbow", ["prio"] = "Hunter",},
{["loot_id"] = "50643", ["loot_name"] = "Shoulders of Mercy Killing", ["prio"] = "FFA",},
{["loot_id"] = "49991", ["loot_name"] = "Shoulders of Mercy Killing", ["prio"] = "FFA",},
{["loot_id"] = "50651", ["loot_name"] = "The Lady's Brittle Bracers", ["prio"] = "Shadow, Mage, Lock",},
{["loot_id"] = "49994", ["loot_name"] = "The Lady's Brittle Bracers", ["prio"] = "Shadow, Mage, Lock",},
{["loot_id"] = "50641", ["loot_name"] = "Heartpierce", ["prio"] = "Assa",},
{["loot_id"] = "49982", ["loot_name"] = "Heartpierce", ["prio"] = "Assa",},
{["loot_id"] = "50649", ["loot_name"] = "Deathwhisper Raiment", ["prio"] = "FFA",},
{["loot_id"] = "49996", ["loot_name"] = "Deathwhisper Raiment", ["prio"] = "FFA",},
{["loot_id"] = "50646", ["loot_name"] = "Cultist's Bloodsoaked Spaulders", ["prio"] = "FFA",},
{["loot_id"] = "49987", ["loot_name"] = "Cultist's Bloodsoaked Spaulders", ["prio"] = "FFA",},
{["loot_id"] = "50652", ["loot_name"] = "Necrophotic Greaves", ["prio"] = "RestoS",},
{["loot_id"] = "49993", ["loot_name"] = "Necrophotic Greaves", ["prio"] = "RestoS",},
{["loot_id"] = "50645", ["loot_name"] = "Leggings of Northern Lights", ["prio"] = "Hunter",},
{["loot_id"] = "49988", ["loot_name"] = "Leggings of Northern Lights", ["prio"] = "Hunter",},
{["loot_id"] = "50639", ["loot_name"] = "Blood-Soaked Saronite Stompers", ["prio"] = "Fury > DPS DK",},
{["loot_id"] = "49983", ["loot_name"] = "Blood-Soaked Saronite Stompers", ["prio"] = "Fury > DPS DK",},
{["loot_id"] = "50650", ["loot_name"] = "Fallen Lord's Handguards", ["prio"] = "HolyPal",},
{["loot_id"] = "49995", ["loot_name"] = "Fallen Lord's Handguards", ["prio"] = "HolyPal",},
{["loot_id"] = "50640", ["loot_name"] = "Broken Ram Skull Helm", ["prio"] = "LK Tank",},
{["loot_id"] = "49986", ["loot_name"] = "Broken Ram Skull Helm", ["prio"] = "LK Tank",},
{["loot_id"] = "50648", ["loot_name"] = "Nibelung", ["prio"] = "Boomy > Ele",},
{["loot_id"] = "49992", ["loot_name"] = "Nibelung", ["prio"] = "Boomy > Ele",},
{["loot_id"] = "50644", ["loot_name"] = "Ring of Maddening Whispers", ["prio"] = "Disc",},
{["loot_id"] = "49990", ["loot_name"] = "Ring of Maddening Whispers", ["prio"] = "Disc",},
{["loot_id"] = "50642", ["loot_name"] = "Juggernaut Band", ["prio"] = "LK Tank",},
{["loot_id"] = "49985", ["loot_name"] = "Juggernaut Band", ["prio"] = "LK Tank",},
{["loot_id"] = "50647", ["loot_name"] = "Ahn'kahar Onyx Neckguard", ["prio"] = "UDK > Ret",},
{["loot_id"] = "49989", ["loot_name"] = "Ahn'kahar Onyx Neckguard", ["prio"] = "UDK > Ret",},
{["loot_id"] = "50654", ["loot_name"] = "Scourgeborne Waraxe", ["prio"] = "Combat",},
{["loot_id"] = "50411", ["loot_name"] = "Scourgeborne Waraxe", ["prio"] = "Combat",},
{["loot_id"] = "50663", ["loot_name"] = "Gunship Captain's Mittens", ["prio"] = "Boomy,Mage",},
{["loot_id"] = "50011", ["loot_name"] = "Gunship Captain's Mittens", ["prio"] = "Boomy,Mage",},
{["loot_id"] = "50661", ["loot_name"] = "Corp'rethar Ceremonial Crown", ["prio"] = "FFA",},
{["loot_id"] = "50006", ["loot_name"] = "Corp'rethar Ceremonial Crown", ["prio"] = "FFA",},
{["loot_id"] = "50656", ["loot_name"] = "Ikfirus's Sack of Wonder", ["prio"] = "Rogue",},
{["loot_id"] = "50001", ["loot_name"] = "Ikfirus's Sack of Wonder", ["prio"] = "Rogue",},
{["loot_id"] = "50665", ["loot_name"] = "Boots of Unnatural Growth", ["prio"] = "RestoD",},
{["loot_id"] = "50009", ["loot_name"] = "Boots of Unnatural Growth", ["prio"] = "RestoD",},
{["loot_id"] = "50655", ["loot_name"] = "Scourge Hunter's Vambraces", ["prio"] = "Hunter",},
{["loot_id"] = "50000", ["loot_name"] = "Scourge Hunter's Vambraces", ["prio"] = "Hunter",},
{["loot_id"] = "50660", ["loot_name"] = "Boneguard Commander's Pauldrons", ["prio"] = "FFA",},
{["loot_id"] = "50003", ["loot_name"] = "Boneguard Commander's Pauldrons", ["prio"] = "FFA",},
{["loot_id"] = "50667", ["loot_name"] = "Waistband of Righteous Fury", ["prio"] = "HolyPal",},
{["loot_id"] = "50010", ["loot_name"] = "Waistband of Righteous Fury", ["prio"] = "HolyPal",},
{["loot_id"] = "50659", ["loot_name"] = "Polar Bear Claw Bracers", ["prio"] = "DPS DK,Ret > Fury",},
{["loot_id"] = "50002", ["loot_name"] = "Polar Bear Claw Bracers", ["prio"] = "DPS DK,Ret > Fury",},
{["loot_id"] = "50653", ["loot_name"] = "Shadowvault Slayer's Cloak", ["prio"] = "Enh,Ret,Assa",},
{["loot_id"] = "49998", ["loot_name"] = "Shadowvault Slayer's Cloak", ["prio"] = "Enh,Ret,Assa",},
{["loot_id"] = "50657", ["loot_name"] = "Skeleton Lord's Circle", ["prio"] = "DPS DK,Fury,Ret",},
{["loot_id"] = "49999", ["loot_name"] = "Skeleton Lord's Circle", ["prio"] = "DPS DK,Fury,Ret",},
{["loot_id"] = "50664", ["loot_name"] = "Ring of Rapid Ascent", ["prio"] = "DPS > Healer",},
{["loot_id"] = "50008", ["loot_name"] = "Ring of Rapid Ascent", ["prio"] = "DPS > Healer",},
{["loot_id"] = "50658", ["loot_name"] = "Amulet of the Silent Eulogy", ["prio"] = "Demo,Mage,Shadow,Ele",},
{["loot_id"] = "50005", ["loot_name"] = "Amulet of the Silent Eulogy", ["prio"] = "Demo,Mage,Shadow,Ele",},
{["loot_id"] = "50366", ["loot_name"] = "Althor's Abacus", ["prio"] = "Healer > HPal",},
{["loot_id"] = "50359", ["loot_name"] = "Althor's Abacus", ["prio"] = "Healer > HPal",},
{["loot_id"] = "50352", ["loot_name"] = "Corpse Tongue Coin", ["prio"] = "FFA",},
{["loot_id"] = "50349", ["loot_name"] = "Corpse Tongue Coin", ["prio"] = "FFA",},
{["loot_id"] = "50672", ["loot_name"] = "Bloodvenom Blade", ["prio"] = "Rogue, DPS DK",},
{["loot_id"] = "50412", ["loot_name"] = "Bloodvenom Blade", ["prio"] = "Rogue, DPS DK",},
{["loot_id"] = "50670", ["loot_name"] = "Toskk's Maximized Wristguards", ["prio"] = "Feral, Rogue, Fury",},
{["loot_id"] = "50333", ["loot_name"] = "Toskk's Maximized Wristguards", ["prio"] = "Feral, Rogue, Fury",},
{["loot_id"] = "50671", ["loot_name"] = "Belt of the Blood Nova", ["prio"] = "RestoS > HPal",},
{["loot_id"] = "50015", ["loot_name"] = "Belt of the Blood Nova", ["prio"] = "RestoS > HPal",},
{["loot_id"] = "50668", ["loot_name"] = "Greatcloak of the Turned Champion", ["prio"] = "Demo >  RestoD",},
{["loot_id"] = "50014", ["loot_name"] = "Greatcloak of the Turned Champion", ["prio"] = "Demo >  RestoD",},
{["loot_id"] = "50363", ["loot_name"] = "Deathbringer's Will", ["prio"] = "Feral,Fury > any DPS > UDK",},
{["loot_id"] = "50362", ["loot_name"] = "Deathbringer's Will", ["prio"] = "Feral,Fury > any DPS > UDK",},
{["loot_id"] = "50699", ["loot_name"] = "Plague Scientist's Boots", ["prio"] = "Affli,Shadow > Mage,Boomy,Ele > Heal",},
{["loot_id"] = "50062", ["loot_name"] = "Plague Scientist's Boots", ["prio"] = "Affli,Shadow > Mage,Boomy,Ele > Heal",},
{["loot_id"] = "50694", ["loot_name"] = "Plaguebringer's Stained Pants", ["prio"] = "Affli,Shadow,Boomy,Ele > HPal",},
{["loot_id"] = "50056", ["loot_name"] = "Plaguebringer's Stained Pants", ["prio"] = "Affli,Shadow,Boomy,Ele > HPal",},
{["loot_id"] = "50702", ["loot_name"] = "Lingering Illness", ["prio"] = "Demo, Disc",},
{["loot_id"] = "50063", ["loot_name"] = "Lingering Illness", ["prio"] = "Demo, Disc",},
{["loot_id"] = "50697", ["loot_name"] = "Gangrenous Leggings", ["prio"] = "Combat",},
{["loot_id"] = "50042", ["loot_name"] = "Gangrenous Leggings", ["prio"] = "Combat",},
{["loot_id"] = "50696", ["loot_name"] = "Leather of Stitched Scourge Parts", ["prio"] = "FFA",},
{["loot_id"] = "50041", ["loot_name"] = "Leather of Stitched Scourge Parts", ["prio"] = "FFA",},
{["loot_id"] = "50689", ["loot_name"] = "Carapace of Forgotten Kings", ["prio"] = "Enha",},
{["loot_id"] = "50038", ["loot_name"] = "Carapace of Forgotten Kings", ["prio"] = "Enha",},
{["loot_id"] = "50703", ["loot_name"] = "Unclean Surgical Gloves", ["prio"] = "RestoS",},
{["loot_id"] = "50064", ["loot_name"] = "Unclean Surgical Gloves", ["prio"] = "RestoS",},
{["loot_id"] = "50698", ["loot_name"] = "Horrific Flesh Epaulets", ["prio"] = "Shaman",},
{["loot_id"] = "50059", ["loot_name"] = "Horrific Flesh Epaulets", ["prio"] = "Shaman",},
{["loot_id"] = "50688", ["loot_name"] = "Nerub'ar Stalker's Cord", ["prio"] = "Hunter",},
{["loot_id"] = "50413", ["loot_name"] = "Nerub'ar Stalker's Cord", ["prio"] = "Hunter",},
{["loot_id"] = "50692", ["loot_name"] = "Black Bruise", ["prio"] = "Enha > Combat",},
{["loot_id"] = "50035", ["loot_name"] = "Black Bruise", ["prio"] = "Enha > Combat",},
{["loot_id"] = "50690", ["loot_name"] = "Fleshrending Gauntlets", ["prio"] = "Ret",},
{["loot_id"] = "50037", ["loot_name"] = "Fleshrending Gauntlets", ["prio"] = "Ret",},
{["loot_id"] = "50701", ["loot_name"] = "Faceplate of the Forgotten", ["prio"] = "HolyPal",},
{["loot_id"] = "50060", ["loot_name"] = "Faceplate of the Forgotten", ["prio"] = "HolyPal",},
{["loot_id"] = "50691", ["loot_name"] = "Belt of Broken Bones", ["prio"] = "LK Tank",},
{["loot_id"] = "50036", ["loot_name"] = "Belt of Broken Bones", ["prio"] = "LK Tank",},
{["loot_id"] = "50695", ["loot_name"] = "Distant Land", ["prio"] = "Feral > Hunter",},
{["loot_id"] = "50040", ["loot_name"] = "Distant Land", ["prio"] = "Feral > Hunter",},
{["loot_id"] = "50693", ["loot_name"] = "Might of Blight", ["prio"] = "DPS DK > Ret",},
{["loot_id"] = "50414", ["loot_name"] = "Might of Blight", ["prio"] = "DPS DK > Ret",},
{["loot_id"] = "50700", ["loot_name"] = "Holiday's Grace", ["prio"] = "Disc",},
{["loot_id"] = "50061", ["loot_name"] = "Holiday's Grace", ["prio"] = "Disc",},
{["loot_id"] = "50686", ["loot_name"] = "Death Surgeon's Sleeves", ["prio"] = "Demo > Disc > Mage",},
{["loot_id"] = "50032", ["loot_name"] = "Death Surgeon's Sleeves", ["prio"] = "Demo > Disc > Mage",},
{["loot_id"] = "50676", ["loot_name"] = "Rib Spreader", ["prio"] = "Rogue",},
{["loot_id"] = "50016", ["loot_name"] = "Rib Spreader", ["prio"] = "Rogue",},
{["loot_id"] = "50675", ["loot_name"] = "Aldriana's Gloves of Secrecy", ["prio"] = "Fury,Rogue > Feral",},
{["loot_id"] = "50021", ["loot_name"] = "Aldriana's Gloves of Secrecy", ["prio"] = "Fury,Rogue > Feral",},
{["loot_id"] = "50679", ["loot_name"] = "Helm of the Elder Moon", ["prio"] = "FFA",},
{["loot_id"] = "50026", ["loot_name"] = "Helm of the Elder Moon", ["prio"] = "FFA",},
{["loot_id"] = "50673", ["loot_name"] = "Dual-Bladed Pauldrons", ["prio"] = "FFA",},
{["loot_id"] = "50022", ["loot_name"] = "Dual-Bladed Pauldrons", ["prio"] = "FFA",},
{["loot_id"] = "50687", ["loot_name"] = "Bloodsunder's Bracers", ["prio"] = "Ele, RestoS > Enha",},
{["loot_id"] = "50030", ["loot_name"] = "Bloodsunder's Bracers", ["prio"] = "Ele, RestoS > Enha",},
{["loot_id"] = "50685", ["loot_name"] = "Trauma", ["prio"] = "FFA",},
{["loot_id"] = "50028", ["loot_name"] = "Trauma", ["prio"] = "FFA",},
{["loot_id"] = "50680", ["loot_name"] = "Rot-Resistant Breastplate", ["prio"] = "HolyPal",},
{["loot_id"] = "50027", ["loot_name"] = "Rot-Resistant Breastplate", ["prio"] = "HolyPal",},
{["loot_id"] = "50681", ["loot_name"] = "Blightborne Warplate", ["prio"] = "FFA",},
{["loot_id"] = "50024", ["loot_name"] = "Blightborne Warplate", ["prio"] = "FFA",},
{["loot_id"] = "50674", ["loot_name"] = "Raging Behemoth's Shoulderplates", ["prio"] = "FFA",},
{["loot_id"] = "50020", ["loot_name"] = "Raging Behemoth's Shoulderplates", ["prio"] = "FFA",},
{["loot_id"] = "50684", ["loot_name"] = "Corpse-Impaling Spike", ["prio"] = "Affli,Mage,Shadow",},
{["loot_id"] = "50033", ["loot_name"] = "Corpse-Impaling Spike", ["prio"] = "Affli,Mage,Shadow",},
{["loot_id"] = "50677", ["loot_name"] = "Winding Sheet", ["prio"] = "UDK",},
{["loot_id"] = "50019", ["loot_name"] = "Winding Sheet", ["prio"] = "UDK",},
{["loot_id"] = "50678", ["loot_name"] = "Seal of Many Mouths", ["prio"] = "Combat",},
{["loot_id"] = "50025", ["loot_name"] = "Seal of Many Mouths", ["prio"] = "Combat",},
{["loot_id"] = "50682", ["loot_name"] = "Bile-Encrusted Medallion", ["prio"] = "LK Tank",},
{["loot_id"] = "50023", ["loot_name"] = "Bile-Encrusted Medallion", ["prio"] = "LK Tank",},
{["loot_id"] = "50353", ["loot_name"] = "Dislodged Foreign Object", ["prio"] = "Caster DPS",},
{["loot_id"] = "50348", ["loot_name"] = "Dislodged Foreign Object", ["prio"] = "Caster DPS",},
{["loot_id"] = "50708", ["loot_name"] = "Last Word", ["prio"] = "FFA",},
{["loot_id"] = "50179", ["loot_name"] = "Last Word", ["prio"] = "FFA",},
{["loot_id"] = "50707", ["loot_name"] = "Astrylian's Sutured Cinch", ["prio"] = "Ret > Rogue,Feral",},
{["loot_id"] = "50067", ["loot_name"] = "Astrylian's Sutured Cinch", ["prio"] = "Ret > Rogue,Feral",},
{["loot_id"] = "50705", ["loot_name"] = "Professor's Bloodied Smock", ["prio"] = "FFA",},
{["loot_id"] = "50069", ["loot_name"] = "Professor's Bloodied Smock", ["prio"] = "FFA",},
{["loot_id"] = "50704", ["loot_name"] = "Rigormortis", ["prio"] = "Mages, Locks",},
{["loot_id"] = "50068", ["loot_name"] = "Rigormortis", ["prio"] = "Mages, Locks",},
{["loot_id"] = "50706", ["loot_name"] = "Tiny Abomination in a Jar", ["prio"] = "Ret > Assa",},
{["loot_id"] = "50351", ["loot_name"] = "Tiny Abomination in a Jar", ["prio"] = "Ret > Assa",},
{["loot_id"] = "50603", ["loot_name"] = "Cryptmaker", ["prio"] = "Fury,Ret  > Feral,Hunter > BDK",},
{["loot_id"] = "49919", ["loot_name"] = "Cryptmaker", ["prio"] = "Fury,Ret  > Feral,Hunter > BDK",},
{["loot_id"] = "50717", ["loot_name"] = "Sanguine Silk Robes", ["prio"] = "Demolock > RestoD",},
{["loot_id"] = "50172", ["loot_name"] = "Sanguine Silk Robes", ["prio"] = "Demolock > RestoD",},
{["loot_id"] = "50722", ["loot_name"] = "San'layn Ritualist Gloves", ["prio"] = "Disc > Shadow,Boomy",},
{["loot_id"] = "50176", ["loot_name"] = "San'layn Ritualist Gloves", ["prio"] = "Disc > Shadow,Boomy",},
{["loot_id"] = "50713", ["loot_name"] = "Geistlord's Punishment Sack", ["prio"] = "FFA",},
{["loot_id"] = "50073", ["loot_name"] = "Geistlord's Punishment Sack", ["prio"] = "FFA",},
{["loot_id"] = "50715", ["loot_name"] = "Shoulders of Frost-Tipped Thorns", ["prio"] = "FFA",},
{["loot_id"] = "50171", ["loot_name"] = "Shoulders of Frost-Tipped Thorns", ["prio"] = "FFA",},
{["loot_id"] = "50723", ["loot_name"] = "Mail of Crimson Coins", ["prio"] = "RestoS",},
{["loot_id"] = "50177", ["loot_name"] = "Mail of Crimson Coins", ["prio"] = "RestoS",},
{["loot_id"] = "50711", ["loot_name"] = "Treads of the Wasteland", ["prio"] = "SV Hunter,Enha",},
{["loot_id"] = "50071", ["loot_name"] = "Treads of the Wasteland", ["prio"] = "SV Hunter,Enha",},
{["loot_id"] = "50719", ["loot_name"] = "Shadow Silk Spindle", ["prio"] = "Caster*,Healer* > HPal",},
{["loot_id"] = "50173", ["loot_name"] = "Shadow Silk Spindle", ["prio"] = "Caster*,Healer* > HPal",},
{["loot_id"] = "50710", ["loot_name"] = "Keleseth's Seducer", ["prio"] = "Enha",},
{["loot_id"] = "50184", ["loot_name"] = "Keleseth's Seducer", ["prio"] = "Enha",},
{["loot_id"] = "50716", ["loot_name"] = "Taldaram's Plated Fists", ["prio"] = "LK Tank",},
{["loot_id"] = "50075", ["loot_name"] = "Taldaram's Plated Fists", ["prio"] = "LK Tank",},
{["loot_id"] = "50712", ["loot_name"] = "Landsoul's Horned Greathelm", ["prio"] = "FFA",},
{["loot_id"] = "50072", ["loot_name"] = "Landsoul's Horned Greathelm", ["prio"] = "FFA",},
{["loot_id"] = "50721", ["loot_name"] = "Crypt Keeper's Bracers", ["prio"] = "HolyPal",},
{["loot_id"] = "50175", ["loot_name"] = "Crypt Keeper's Bracers", ["prio"] = "HolyPal",},
{["loot_id"] = "50718", ["loot_name"] = "Royal Crimson Cloak", ["prio"] = "LK Tank",},
{["loot_id"] = "50074", ["loot_name"] = "Royal Crimson Cloak", ["prio"] = "LK Tank",},
{["loot_id"] = "50720", ["loot_name"] = "Incarnadine Band of Mending", ["prio"] = "Disc",},
{["loot_id"] = "50174", ["loot_name"] = "Incarnadine Band of Mending", ["prio"] = "Disc",},
{["loot_id"] = "50714", ["loot_name"] = "Valanar's Other Signet Ring", ["prio"] = "Demolock",},
{["loot_id"] = "50170", ["loot_name"] = "Valanar's Other Signet Ring", ["prio"] = "Demolock",},
{["loot_id"] = "50727", ["loot_name"] = "Bloodfall", ["prio"] = "Feral > Hunter > BDK",},
{["loot_id"] = "50178", ["loot_name"] = "Bloodfall", ["prio"] = "Feral > Hunter > BDK",},
{["loot_id"] = "50729", ["loot_name"] = "Icecrown Glacial Wall", ["prio"] = "Tanks (obviously)",},
{["loot_id"] = "50065", ["loot_name"] = "Icecrown Glacial Wall", ["prio"] = "Tanks (obviously)",},
{["loot_id"] = "50725", ["loot_name"] = "Dying Light", ["prio"] = "FFA",},
{["loot_id"] = "50181", ["loot_name"] = "Dying Light", ["prio"] = "FFA",},
{["loot_id"] = "50724", ["loot_name"] = "Blood Queen's Crimson Choker", ["prio"] = "DPS* > Healer*",},
{["loot_id"] = "50182", ["loot_name"] = "Blood Queen's Crimson Choker", ["prio"] = "DPS* > Healer*",},
{["loot_id"] = "50728", ["loot_name"] = "Lana'thel's Chain of Flagellation", ["prio"] = "FDK,BDK(DPS) > Fury,Ret",},
{["loot_id"] = "50180", ["loot_name"] = "Lana'thel's Chain of Flagellation", ["prio"] = "FDK,BDK(DPS) > Fury,Ret",},
{["loot_id"] = "50726", ["loot_name"] = "Bauble of True Blood", ["prio"] = "FFA",},
{["loot_id"] = "50354", ["loot_name"] = "Bauble of True Blood", ["prio"] = "FFA",},
{["loot_id"] = "50629", ["loot_name"] = "Robe of the Waking Nightmare", ["prio"] = "Mage > RestoD",},
{["loot_id"] = "50418", ["loot_name"] = "Robe of the Waking Nightmare", ["prio"] = "Mage > RestoD",},
{["loot_id"] = "50621", ["loot_name"] = "Lungbreaker", ["prio"] = "Assa",},
{["loot_id"] = "50183", ["loot_name"] = "Lungbreaker", ["prio"] = "Assa",},
{["loot_id"] = "50630", ["loot_name"] = "Bracers of Eternal Dreaming", ["prio"] = "Boomie",},
{["loot_id"] = "50417", ["loot_name"] = "Bracers of Eternal Dreaming", ["prio"] = "Boomie",},
{["loot_id"] = "50619", ["loot_name"] = "Anub'ar Stalker's Gloves", ["prio"] = "FFA",},
{["loot_id"] = "50188", ["loot_name"] = "Anub'ar Stalker's Gloves", ["prio"] = "FFA",},
{["loot_id"] = "50626", ["loot_name"] = "Snowstorm Helm", ["prio"] = "FFA",},
{["loot_id"] = "50202", ["loot_name"] = "Snowstorm Helm", ["prio"] = "FFA",},
{["loot_id"] = "50632", ["loot_name"] = "Boots of the Funeral March", ["prio"] = "HolyPal",},
{["loot_id"] = "50416", ["loot_name"] = "Boots of the Funeral March", ["prio"] = "HolyPal",},
{["loot_id"] = "50625", ["loot_name"] = "Grinning Skull Greatboots", ["prio"] = "LK Tank",},
{["loot_id"] = "50190", ["loot_name"] = "Grinning Skull Greatboots", ["prio"] = "LK Tank",},
{["loot_id"] = "50624", ["loot_name"] = "Scourge Reaver's Legplates", ["prio"] = "UDK",},
{["loot_id"] = "50192", ["loot_name"] = "Scourge Reaver's Legplates", ["prio"] = "UDK",},
{["loot_id"] = "50623", ["loot_name"] = "Leggings of Dying Candles", ["prio"] = "HolyPal",},
{["loot_id"] = "50199", ["loot_name"] = "Leggings of Dying Candles", ["prio"] = "HolyPal",},
{["loot_id"] = "50620", ["loot_name"] = "Coldwraith Links", ["prio"] = "Fury,FDK,BDK(DPS) > Unholy",},
{["loot_id"] = "50187", ["loot_name"] = "Coldwraith Links", ["prio"] = "Fury,FDK,BDK(DPS) > Unholy",},
{["loot_id"] = "50631", ["loot_name"] = "Nightmare Ender", ["prio"] = "Demolock, Disc",},
{["loot_id"] = "50472", ["loot_name"] = "Nightmare Ender", ["prio"] = "Demolock, Disc",},
{["loot_id"] = "50628", ["loot_name"] = "Frostbinder's Shredded Cape", ["prio"] = "DPS* > Healer*",},
{["loot_id"] = "50205", ["loot_name"] = "Frostbinder's Shredded Cape", ["prio"] = "DPS* > Healer*",},
{["loot_id"] = "50618", ["loot_name"] = "Frostbrood Sapphire Ring", ["prio"] = "Hunter > Fury",},
{["loot_id"] = "50186", ["loot_name"] = "Frostbrood Sapphire Ring", ["prio"] = "Hunter > Fury",},
{["loot_id"] = "50627", ["loot_name"] = "Noose of Malachite", ["prio"] = "ProtP > ProtW",},
{["loot_id"] = "50195", ["loot_name"] = "Noose of Malachite", ["prio"] = "ProtP > ProtW",},
{["loot_id"] = "50622", ["loot_name"] = "Devium's Eternally Cold Ring", ["prio"] = "LK Tank",},
{["loot_id"] = "50185", ["loot_name"] = "Devium's Eternally Cold Ring", ["prio"] = "LK Tank",},
{["loot_id"] = "50635", ["loot_name"] = "Sundial of Eternal Dusk", ["prio"] = "Rdruid/Disc > Demolock",},
{["loot_id"] = "50423", ["loot_name"] = "Sundial of Eternal Dusk", ["prio"] = "Rdruid/Disc > Demolock",},
{["loot_id"] = "50636", ["loot_name"] = "Memory of Malygos", ["prio"] = "Demolock > RestoD",},
{["loot_id"] = "50424", ["loot_name"] = "Memory of Malygos", ["prio"] = "Demolock > RestoD",},
{["loot_id"] = "50633", ["loot_name"] = "Sindragosa's Cruel Claw", ["prio"] = "Feral,Rogue,Hunter > Fury,Ret",},
{["loot_id"] = "50421", ["loot_name"] = "Sindragosa's Cruel Claw", ["prio"] = "Feral,Rogue,Hunter > Fury,Ret",},
{["loot_id"] = "50365", ["loot_name"] = "Phylactery of the Nameless Lich", ["prio"] = "Mage*,Demolock*",},
{["loot_id"] = "50360", ["loot_name"] = "Phylactery of the Nameless Lich", ["prio"] = "Mage*,Demolock*",},
{["loot_id"] = "50364", ["loot_name"] = "Sindragosa's Flawless Fang", ["prio"] = "LK Tank",},
{["loot_id"] = "50361", ["loot_name"] = "Sindragosa's Flawless Fang", ["prio"] = "LK Tank",},
{["loot_id"] = "50737", ["loot_name"] = "Havoc's Call, Blade of Lordaeron Kings", ["prio"] = "DPS DK, Combat > Enha",},
{["loot_id"] = "50012", ["loot_name"] = "Havoc's Call, Blade of Lordaeron Kings", ["prio"] = "DPS DK, Combat > Enha",},
{["loot_id"] = "50738", ["loot_name"] = "Mithrios, Bronzebeard's Legacy", ["prio"] = "Tanks (obviously)",},
{["loot_id"] = "49997", ["loot_name"] = "Mithrios, Bronzebeard's Legacy", ["prio"] = "Tanks (obviously)",},
{["loot_id"] = "50735", ["loot_name"] = "Oathbinder, Charge of the Ranger-General", ["prio"] = "Feral > Hunter > BDK",},
{["loot_id"] = "50425", ["loot_name"] = "Oathbinder, Charge of the Ranger-General", ["prio"] = "Feral > Hunter > BDK",},
{["loot_id"] = "50730", ["loot_name"] = "Glorenzelg, High-Blade of the Silver Hand", ["prio"] = "Fury > Ret,BDK",},
{["loot_id"] = "50070", ["loot_name"] = "Glorenzelg, High-Blade of the Silver Hand", ["prio"] = "Fury > Ret,BDK",},
{["loot_id"] = "50733", ["loot_name"] = "Fal'inrush, Defender of Quel'thalas", ["prio"] = "Hunter",},
{["loot_id"] = "49981", ["loot_name"] = "Fal'inrush, Defender of Quel'thalas", ["prio"] = "Hunter",},
{["loot_id"] = "50736", ["loot_name"] = "Heaven's Fall, Kryss of a Thousand Lies", ["prio"] = "Rogue",},
{["loot_id"] = "50426", ["loot_name"] = "Heaven's Fall, Kryss of a Thousand Lies", ["prio"] = "Rogue",},
{["loot_id"] = "50734", ["loot_name"] = "Royal Scepter of Terenas II", ["prio"] = "Shadow,Boomy,Ele,Enha > Healer",},
{["loot_id"] = "50428", ["loot_name"] = "Royal Scepter of Terenas II", ["prio"] = "Shadow,Boomy,Ele,Enha > Healer",},
{["loot_id"] = "50732", ["loot_name"] = "Bloodsurge, Kel'thuzad's Blade of Agony", ["prio"] = "Mage, Affli > Demo",},
{["loot_id"] = "50427", ["loot_name"] = "Bloodsurge, Kel'thuzad's Blade of Agony", ["prio"] = "Mage, Affli > Demo",},
{["loot_id"] = "50731", ["loot_name"] = "Archus, Greatstaff of Antonidas", ["prio"] = "DPS > Healer > HPal",},
{["loot_id"] = "50429", ["loot_name"] = "Archus, Greatstaff of Antonidas", ["prio"] = "DPS > Healer > HPal",},
{["loot_id"] = "50449", ["loot_name"] = "Stiffened Corpse Shoulderpads", ["prio"] = "*BOE* Auction House",},
{["loot_id"] = "50444", ["loot_name"] = "Rowan's Rifle of Silver Bullets", ["prio"] = "*BOE* Auction House",},
{["loot_id"] = "50450", ["loot_name"] = "Leggings of Dubious Charms", ["prio"] = "*BOE* Auction House",},
{["loot_id"] = "50451", ["loot_name"] = "Belt of the Lonely Noble", ["prio"] = "*BOE* HPal > Auction House",},
{["loot_id"] = "50453", ["loot_name"] = "Ring of Rotting Sinew", ["prio"] = "*BOE* Auction House",},
{["loot_id"] = "50447", ["loot_name"] = "Harbinger's Bone Band", ["prio"] = "*BOE* Auction House",},
{["loot_id"] = "50452", ["loot_name"] = "Wodin's Lucky Necklace", ["prio"] = "*BOE* Any physical DPS",},
}
